// Code generated by alef — DO NOT EDIT.
// alef:hash:1af575cfdc81b62783933cad6cf7cbc43c02c11e0d0152d07f63ddef247aa694
package xberg

// RequireNativeSetup_1_1_3 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_1_3 = "1.1.3"
