# Generated by alef. Do not edit by hand.
# alef:hash:7967e3a7c8c79b16650c12e16c8884aa841c0a4551dbe895ee9b4a67297cbcae
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.** { *; }
