# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:33da5d9a5aec94b0e34ca4eafa15ab2fc3bbf1aac75570bc539a6fae4bea2744
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ArchiveEntry do
  @moduledoc """
  A single file extracted from an archive.

  When archives (ZIP, TAR, 7Z, GZIP) are extracted with recursive extraction
  enabled, each processable file produces its own full `ExtractedDocument`.
  """

  @typedoc "A single file extracted from an archive."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          mime_type: String.t() | nil,
          result: Xberg.ExtractedDocument.t()
        }

  defstruct path: nil,
            mime_type: nil,
            result: nil
end
