# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c72b316f05bcbe746a60ca7473a150b09864b903195ea636b588f1d6ceb8f6a0
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.BrowserBackend do
  @moduledoc "Browser backend used for JavaScript rendering."

  @typedoc "Browser backend used for JavaScript rendering."
  @type t :: :chromiumoxide | :native

  @chromiumoxide :chromiumoxide
  @native :native

  @doc "Existing Chromium/CDP backend powered by chromiumoxide."
  @spec chromiumoxide() :: t()
  def chromiumoxide, do: @chromiumoxide
  @doc "Crawlberg-owned native browser backend derived from Obscura."
  @spec native() :: t()
  def native, do: @native

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:chromiumoxide), do: "chromiumoxide"
  def wire_value(:native), do: "native"
end
