# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0fa42aa9e63eeff9d8cccb555f3199f9c1c4e60c82e576c46eb8fcfda6c6a0f9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.BrowserWait do
  @moduledoc "Wait strategy for browser page rendering."

  @typedoc "Wait strategy for browser page rendering."
  @type t :: :network_idle | :selector | :fixed

  @network_idle :network_idle
  @selector :selector
  @fixed :fixed

  @doc "Wait until network activity is idle."
  @spec network_idle() :: t()
  def network_idle, do: @network_idle
  @doc "Wait for a specific CSS selector to appear in the DOM."
  @spec selector() :: t()
  def selector, do: @selector
  @doc "Wait for a fixed duration after navigation."
  @spec fixed() :: t()
  def fixed, do: @fixed

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:network_idle), do: "network_idle"
  def wire_value(:selector), do: "selector"
  def wire_value(:fixed), do: "fixed"
end
