# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:76597448925d5450ccbba997b8633efccea9a1f2b8348702ced73575fdb86620
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Citation do
  @moduledoc """
  A structured citation from a citation block.

  Parsed from entries like:
  `[^srcN]: source, locator, excerpt: "text"`
  """

  @typedoc "A structured citation from a citation block."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          source: String.t() | nil,
          locator: String.t() | nil,
          excerpt: String.t() | nil
        }

  defstruct label: nil,
            source: nil,
            locator: nil,
            excerpt: nil
end
