# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:91c7ddebd05393159a52efe19e95bef5505f1485543686542603a8ba0aad2a3d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ClassificationLabel do
  @moduledoc "A single label + confidence pair."

  @typedoc "A single label + confidence pair."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          confidence: float() | nil
        }

  defstruct label: nil,
            confidence: nil
end
