# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:78d363c920d6882bf1344d29f8a18ec98ea55e5afc5c3a86fa407eafbf61cbf1
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.CodeMetadata do
  @moduledoc """
  Code-format metadata: the structural chunks produced by tree-sitter parsing.

  Wrapped by [`FormatMetadata::Code`]. Kept as a named struct (rather than an inline
  enum-variant body) so serde can tag it under internal tagging and utoipa can emit a
  referenceable `CodeMetadata` component in the OpenAPI schema.
  """

  @typedoc "Code-format metadata: the structural chunks produced by tree-sitter parsing."
  @type t :: %__MODULE__{
          chunks: [Xberg.CodeChunkInfo.t()],
          data: Xberg.CodeDataNode.t() | nil
        }

  defstruct chunks: [],
            data: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
