# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d1d334a57b73bb5ca6511c7656be99ec8145648ccd02257ba7712c8c80d3ef8c
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.CodeDataAttribute do
  @moduledoc """
  An XML-style attribute attached to an [`Element`](CodeDataNodeKind::Element) node.

  Populated only for `CodeDataNodeKind::Element`; always empty for `KeyValue` and
  `Sequence` nodes.
  """

  @typedoc "An XML-style attribute attached to an [`Element`](CodeDataNodeKind::Element) node."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          value: String.t() | nil,
          byte_start: non_neg_integer(),
          byte_end: non_neg_integer()
        }

  defstruct name: nil,
            value: nil,
            byte_start: 0,
            byte_end: 0
end
