# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:02fcd5d91978c7e7ba92a711c38785a3d1ea5fabb289994dc67b29cc3611ccfc
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DbfMetadata do
  @moduledoc "dBASE (DBF) file metadata."

  @typedoc "dBASE (DBF) file metadata."
  @type t :: %__MODULE__{
          record_count: non_neg_integer(),
          field_count: non_neg_integer(),
          fields: [Xberg.DbfFieldInfo.t()]
        }

  defstruct record_count: 0,
            field_count: 0,
            fields: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
