# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:00b5745cc2adb88a436ed9280f641ce716f255d6f61a51fc84126d9df73d3ca1
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DetectResponse do
  @moduledoc "MIME type detection response."

  @typedoc "MIME type detection response."
  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          filename: String.t() | nil
        }

  defstruct mime_type: nil,
            filename: nil
end
