# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9890bef182a6bff77ce135867e114334ea7a4eb1697618f4013991d27695b9fb
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DjotAttributeGroup do
  @moduledoc "Attributes associated with a named Djot element."

  @typedoc "Attributes associated with a named Djot element."
  @type t :: %__MODULE__{
          identifier: String.t() | nil,
          attributes: Xberg.Attributes.t()
        }

  defstruct identifier: nil,
            attributes: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
