# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4bcb3ba6272b6e1238d5fbb6159084eaeaba856773e3473d294d649e1689f1f1
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DjotLink do
  @moduledoc "Link element in Djot."

  @typedoc "Link element in Djot."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          attributes: Xberg.Attributes.t() | nil
        }

  defstruct url: nil,
            text: nil,
            title: nil,
            attributes: nil
end
