# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0713c0c736a88d2a17947d455eebcdf733d2cba1aaebd260ecaf5619543ab8f0
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DocumentStructure do
  @moduledoc """
  Top-level structured document representation.

  A flat array of nodes with index-based parent/child references forming a tree.
  Root-level nodes have `parent: None`. Use `body_roots()` and `furniture_roots()`
  to iterate over top-level content by layer.

  # Validation

  Call `validate()` after construction to verify all node indices are in bounds
  and parent-child relationships are bidirectionally consistent.
  """

  @typedoc "Top-level structured document representation."
  @type t :: %__MODULE__{
          nodes: [Xberg.DocumentNode.t()],
          source_format: String.t() | nil,
          relationships: [Xberg.DocumentRelationship.t()],
          node_types: [String.t()]
        }

  defstruct nodes: [],
            source_format: nil,
            relationships: [],
            node_types: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
