# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4510c053cb1167374ad89b553bed0c873bf2b2aa760bd21a8dd292a24fc5ae1
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DocumentRevision do
  @moduledoc """
  A single tracked change embedded in a document.

  Populated by per-format extractors that understand change-tracking metadata
  (DOCX `w:ins`/`w:del`/`w:rPrChange`, ODT `text:change-*`, …). Every
  extractor defaults to `ExtractedDocument.revisions = None` until a
  format-specific implementation is added.
  """

  @typedoc "A single tracked change embedded in a document."
  @type t :: %__MODULE__{
          revision_id: String.t() | nil,
          author: String.t() | nil,
          timestamp: String.t() | nil,
          kind: Xberg.RevisionKind.t(),
          anchor: Xberg.RevisionAnchor.t() | nil,
          delta: Xberg.RevisionDelta.t()
        }

  defstruct revision_id: nil,
            author: nil,
            timestamp: nil,
            kind: :insertion,
            anchor: nil,
            delta: nil
end
