# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:414ccbf088e396f2da54fc8da58a8a0d6d42acf98fe85a75eb1134193ce9e5ef
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  @typedoc "A resolved relationship between two nodes in the document tree."
  @type t :: %__MODULE__{
          source: non_neg_integer(),
          target: non_neg_integer(),
          kind: Xberg.RelationshipKind.t()
        }

  defstruct source: 0,
            target: 0,
            kind: :footnote_reference
end
