# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc3aab6d542a01aea9ef97523b5e8aaff703d1f5986a356721abe3e063e7c2dd
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DocumentBoundary do
  @moduledoc "Detected document boundary within a PDF."

  @typedoc "Detected document boundary within a PDF."
  @type t :: %__MODULE__{
          start_page: non_neg_integer(),
          end_page: non_neg_integer(),
          confidence: float(),
          reason: Xberg.BoundaryReason.t()
        }

  defstruct start_page: 0,
            end_page: 0,
            confidence: 0.0,
            reason: :start
end
