# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:368cf9e46b7c0d677d0c2a0ebf4ff4df2aeecf961c141c0cf5112c5ed8756879
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DocumentNode do
  @moduledoc """
  A single node in the document tree.

  Each node has deterministic `id`, typed `content`, optional `parent`/`children`
  for tree structure, and metadata like page number, bounding box, and content layer.
  """

  @typedoc "A single node in the document tree."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          content: Xberg.NodeContent.t(),
          parent: non_neg_integer() | nil,
          children: [non_neg_integer()],
          content_layer: Xberg.ContentLayer.t(),
          page: non_neg_integer() | nil,
          page_end: non_neg_integer() | nil,
          bbox: Xberg.BoundingBox.t() | nil,
          annotations: [Xberg.TextAnnotation.t()],
          attributes: map() | nil
        }

  defstruct id: nil,
            content: :title,
            parent: nil,
            children: [],
            content_layer: :body,
            page: nil,
            page_end: nil,
            bbox: nil,
            annotations: [],
            attributes: nil
end
