# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:256b1ff1dd8228c598d902da264fbd1cfa62887350edf0eb1db65c9f51a5a1c0
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DocumentMetadata do
  @moduledoc "Metadata about a document for analysis."

  @typedoc "Metadata about a document for analysis."
  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          size_bytes: non_neg_integer(),
          page_count: non_neg_integer() | nil,
          force_ocr: boolean(),
          user_chunk_config: Xberg.UserChunkConfig.t() | nil,
          chunking_enabled: boolean()
        }

  defstruct mime_type: nil,
            size_bytes: 0,
            page_count: nil,
            force_ocr: false,
            user_chunk_config: nil,
            chunking_enabled: false
end
