# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1dcc1311b1bb872a6f300d158e3e7d26e725d0cbf33a2b8cd29083bb0a3f0557
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Element do
  @moduledoc """
  Semantic element extracted from document.

  Represents a logical unit of content with semantic classification,
  unique identifier, and metadata for tracking origin and position.
  """

  @typedoc "Semantic element extracted from document."
  @type t :: %__MODULE__{
          element_id: String.t() | nil,
          element_type: Xberg.ElementType.t(),
          text: String.t() | nil,
          metadata: Xberg.ElementMetadata.t()
        }

  defstruct element_id: nil,
            element_type: :title,
            text: nil,
            metadata: nil
end
