# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f23a585a873cd7b3e083475e4bc819c2fbc3686f3dc71876dbd3912e8eade5cc
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.EmailConfig do
  @moduledoc "Configuration for email extraction."

  @typedoc "Configuration for email extraction."
  @type t :: %__MODULE__{
          msg_fallback_codepage: non_neg_integer() | nil
        }

  defstruct msg_fallback_codepage: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
