# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0c704df18f7543f5d43ff8594074760c396b0f9bfd415b1a5e5bee20f1efd8b8
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.EmbeddedChanges do
  @moduledoc "Changes to embedded archive children between two results."

  @typedoc "Changes to embedded archive children between two results."
  @type t :: %__MODULE__{
          added: [Xberg.ArchiveEntry.t()],
          removed: [Xberg.ArchiveEntry.t()],
          changed: [Xberg.EmbeddedDiff.t()]
        }

  defstruct added: [],
            removed: [],
            changed: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
