# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:51ab16e2f9909d9b8860f6b52cc0bee5438c6b4b954e3bb2bf911de75cc0f2a3
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ErrorMetadata do
  @moduledoc "Error metadata (for batch operations)."

  @typedoc "Error metadata (for batch operations)."
  @type t :: %__MODULE__{
          error_type: String.t() | nil,
          message: String.t() | nil
        }

  defstruct error_type: nil,
            message: nil
end
