# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d6695df8122a24cb49f7d84fa068bf679d27accbd7ad17ce16d8540f115a2d95
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
          sheets: [Xberg.ExcelSheet.t()],
          metadata: map(),
          revisions: [Xberg.DocumentRevision.t()] | nil
        }

  defstruct sheets: [],
            metadata: %{},
            revisions: nil
end
