# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9e5196b03c6960e9d06248753b628da0c40a1f390c1f535af899a4f028f72277
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ExtractionErrorItem do
  @moduledoc "Non-fatal per-input extraction error captured by [`ExtractionResult`]."

  @typedoc "Non-fatal per-input extraction error captured by [`ExtractionResult`]."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          code: non_neg_integer(),
          error_type: String.t() | nil,
          source: String.t() | nil,
          message: String.t() | nil
        }

  defstruct index: 0,
            code: 0,
            error_type: nil,
            source: nil,
            message: nil
end
