# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:edce52e805848dea0331a176b08fe0dc7d50dd1acb7df7fd39062164792d2951
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ExtractedUri do
  @moduledoc """
  A URI extracted from a document.

  Represents any link, reference, or resource pointer found during extraction.
  The `kind` field classifies the URI semantically, while `label` carries
  optional human-readable display text.
  """

  @typedoc "A URI extracted from a document."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          label: String.t() | nil,
          page: non_neg_integer() | nil,
          kind: Xberg.UriKind.t()
        }

  defstruct url: nil,
            label: nil,
            page: nil,
            kind: :hyperlink
end
