# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:411045874c3ff35e7f0ec43676ebfacc9de377d4426256d919be20d10ac364b3
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.FictionBookMetadata do
  @moduledoc "FictionBook (FB2) metadata."

  @typedoc "FictionBook (FB2) metadata."
  @type t :: %__MODULE__{
          genres: [String.t()],
          sequences: [String.t()],
          annotation: String.t() | nil
        }

  defstruct genres: [],
            sequences: [],
            annotation: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
