# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ff2d5035b6e3de907fb8b82572f27800a6b39e7b0d69a8de0365063e748e387d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.FootnoteAnchor do
  @moduledoc """
  A footnote anchor reference in markdown text.

  Represents a `[^label]` use-site (not a definition).
  """

  @typedoc "A footnote anchor reference in markdown text."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          offset: non_neg_integer()
        }

  defstruct label: nil,
            offset: 0
end
