# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9971d239c8a6a405d23f494132cb3c0b77ba22bcccf8f0213d5a9a00a8cd367
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Footnote do
  @moduledoc "Footnote in Djot."

  @typedoc "Footnote in Djot."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: [Xberg.FormattedBlock.t()]
        }

  defstruct label: nil,
            content: []
end
