# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9ae7ce013a00986f47dfde08e1493e9be8e4559b9cf3cea5bdc010e4c56a87e7
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.FootnoteDefinition do
  @moduledoc """
  A footnote definition from markdown text.

  Represents `[^label]: content` declarations (including multi-line continuations).
  """

  @typedoc "A footnote definition from markdown text."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: String.t() | nil,
          offset: non_neg_integer()
        }

  defstruct label: nil,
            content: nil,
            offset: 0
end
