# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1cb39a0c41da32618a64217b3999573d60037afa8208b0a27eb4793f7dc83490
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.FormulaModel do
  @moduledoc "Formula recognition model selection."

  @typedoc "Formula recognition model selection."
  @type t :: :latex_ocr

  @latex_ocr :latex_ocr

  @doc "RapidLaTeXOCR (MIT, pix2tex-derived): resizer + encoder + decoder ONNX, ~180 MB total, downloaded on demand."
  @spec latex_ocr() :: t()
  def latex_ocr, do: @latex_ocr

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:latex_ocr), do: "latex_ocr"
end
