# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:87fd8e54dcfbafb98814397ce5de74b3832acb080bb50330a9d9549208fb62b4
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.GlmOcrLayoutMode do
  @moduledoc "Page layout mode accepted by `candle-glm-ocr` backend options."

  @typedoc "Page layout mode accepted by `candle-glm-ocr` backend options."
  @type t :: :whole_page | :paired

  @whole_page :whole_page
  @paired :paired

  @spec whole_page() :: t()
  def whole_page, do: @whole_page
  @spec paired() :: t()
  def paired, do: @paired

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:whole_page), do: "whole_page"
  def wire_value(:paired), do: "paired"
end
