# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9b29a6d30bfa0eec1ca0e47f407a5d03532efdef92d17fe9ce8659889edd32c3
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.HeadingContext do
  @moduledoc """
  Heading context for a chunk within a Markdown document.

  Contains the heading hierarchy from document root to this chunk's section.
  """

  @typedoc "Heading context for a chunk within a Markdown document."
  @type t :: %__MODULE__{
          headings: [Xberg.HeadingLevel.t()]
        }

  defstruct headings: []
end
