# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9fbb468b309cfd6deeff606f0c01ff4f3eb9ff2206577cdd509c34f5072ac268
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  @typedoc "A single heading in the hierarchy."
  @type t :: %__MODULE__{
          level: non_neg_integer(),
          text: String.t() | nil
        }

  defstruct level: 0,
            text: nil
end
