# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e5787c8e149e114e54ec1aecd5dd68e486bd21b0dc79114dce293701f9f32e51
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  @typedoc "Header/heading element metadata."
  @type t :: %__MODULE__{
          level: non_neg_integer(),
          text: String.t() | nil,
          id: String.t() | nil,
          depth: non_neg_integer(),
          html_offset: non_neg_integer()
        }

  defstruct level: 0,
            text: nil,
            id: nil,
            depth: 0,
            html_offset: 0

  @doc "Validate that the header level is within valid range (1-6)."
  @spec valid?(t()) :: boolean()
  def valid?(%__MODULE__{level: level}) do
    level >= 1 and level <= 6
  end
end
