# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f6c3dac89a974096aaa5adc22a8483f45c5879d3c353708e146c9c19382bc162
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  @typedoc "Extracted keyword with metadata."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          score: float(),
          algorithm: Xberg.KeywordAlgorithm.t(),
          positions: [non_neg_integer()] | nil
        }

  defstruct text: nil,
            score: 0.0,
            algorithm: :yake,
            positions: nil
end
