# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf3d4ce6154c71653a8473f86d4a2c3f142e133c68d3a80f630c26b7a6ff7efc
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LateInteractionPreset do
  @moduledoc "Static metadata for a bundled ColBERT preset (WASM/Android-safe, no ORT)."

  @typedoc "Static metadata for a bundled ColBERT preset (WASM/Android-safe, no ORT)."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          model_repo: String.t() | nil,
          model_file: String.t() | nil,
          additional_files: [String.t()],
          max_length: non_neg_integer(),
          query_max_length: non_neg_integer(),
          dim: non_neg_integer(),
          description: String.t() | nil
        }

  defstruct name: nil,
            model_repo: nil,
            model_file: nil,
            additional_files: [],
            max_length: 0,
            query_max_length: 0,
            dim: 0,
            description: nil
end
