# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:104e04e1c6181712bea41ab5f53004faf7fb22e69af391d1e0638df9f3d6d0d8
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.MarkdownCodeBlock do
  @moduledoc "A fenced code block extracted from Markdown."

  @typedoc "A fenced code block extracted from Markdown."
  @type t :: %__MODULE__{
          language: String.t() | nil,
          code: String.t() | nil
        }

  defstruct language: nil,
            code: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
