# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e9db1955f0ca63939ff21d0655a42915346f20d9c8873cd8179c20edca0e4d96
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.MarkdownLink do
  @moduledoc "A link extracted from Markdown."

  @typedoc "A link extracted from Markdown."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          url: String.t() | nil
        }

  defstruct text: nil,
            url: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
