# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8f5c2a5c387c173fb31af1f16d86fdb503752ba7b77a52c1c7480130b2ba3c3c
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  @typedoc "Combined paths to all models needed for OCR (backward compatibility)."
  @type t :: %__MODULE__{
          det_model: String.t() | nil,
          cls_model: String.t() | nil,
          rec_model: String.t() | nil,
          dict_file: String.t() | nil
        }

  defstruct det_model: nil,
            cls_model: nil,
            rec_model: nil,
            dict_file: nil
end
