# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2589f0d84eb4810dda39835327ec4ff68623178e9174406ef5f6b20963b52b00
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.NgramRange do
  @moduledoc "Inclusive word-count range used to form keyword candidates."

  @typedoc "Inclusive word-count range used to form keyword candidates."
  @type t :: %__MODULE__{
          min: non_neg_integer(),
          max: non_neg_integer()
        }

  defstruct min: 1,
            max: 3

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
