# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4aa0c0f2627957d6597d453258107bfe5fcc11686d55bff095132bf8ef10e824
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageInfo do
  @moduledoc false

  @type t :: %__MODULE__{
          number: non_neg_integer(),
          title: String.t() | nil,
          dimensions: Xberg.PageDimensions.t() | nil,
          image_count: non_neg_integer() | nil,
          table_count: non_neg_integer() | nil,
          hidden: boolean() | nil,
          is_blank: boolean() | nil,
          has_vector_graphics: boolean()
        }

  defstruct number: 0,
            title: nil,
            dimensions: nil,
            image_count: nil,
            table_count: nil,
            hidden: nil,
            is_blank: nil,
            has_vector_graphics: false
end
