# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ed504e8b18a53bc49eab2cfe29ac3841d400743c6072f70fd1d44717fa93f178
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageSpan do
  @moduledoc """
  A single page covered by a chunk, with an optional bounding box on that page.

  See [`ChunkMetadata::page_spans`] (#1295) for population semantics.
  """

  @typedoc "A single page covered by a chunk, with an optional bounding box on that page."
  @type t :: %__MODULE__{
          page: non_neg_integer(),
          bbox: Xberg.BoundingBox.t() | nil
        }

  defstruct page: 0,
            bbox: nil
end
