# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fe4fe12b4a76914bec88cf4a124cb6c5573106e77ec38ec86537244aa6f0e4cf
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PropertyChange do
  @moduledoc """
  A single run-level or style-level property change.

  Used for revisions that change formatting rather than text content. `from`
  and `to` store normalized property values when the source format exposes
  them; either side may be absent when the format only records one side of the
  change.
  """

  @typedoc "A single run-level or style-level property change."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          from: String.t() | nil,
          to: String.t() | nil
        }

  defstruct name: nil,
            from: nil,
            to: nil
end
