# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:26a5b139dca0a87295ce764ea2cca6c91b98b8983a529c4a0a1ae0d2d0344eb7
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.SitemapUrl do
  @moduledoc "A URL entry from a sitemap."

  @typedoc "A URL entry from a sitemap."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          lastmod: String.t() | nil,
          changefreq: String.t() | nil,
          priority: String.t() | nil
        }

  defstruct url: nil,
            lastmod: nil,
            changefreq: nil,
            priority: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
