# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eef50fb4dbca1e0f80231dd541b589039a1743a0691428fde47b4169ca664964
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.SupportedFormat do
  @moduledoc """
  A supported document format entry.

  Represents a file extension and its corresponding MIME type that Xberg can process.
  """

  @typedoc "A supported document format entry."
  @type t :: %__MODULE__{
          extension: String.t() | nil,
          mime_type: String.t() | nil
        }

  defstruct extension: nil,
            mime_type: nil
end
