# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:acbf4777480c41a7e08dc3afc100d2dff2dc17492d4de70870d747bbec86fde9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.TableDiff do
  @moduledoc "Cell-level changes for a pair of tables that share the same index."

  @typedoc "Cell-level changes for a pair of tables that share the same index."
  @type t :: %__MODULE__{
          from_index: non_neg_integer(),
          to_index: non_neg_integer(),
          cell_changes: [Xberg.CellChange.t()]
        }

  defstruct from_index: 0,
            to_index: 0,
            cell_changes: []
end
