# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:696d5788b25c2e050eee0c33ba6729cd0a0e64d3fc3f319260a9c67c28155c41
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.TextAnnotation do
  @moduledoc """
  Inline text annotation — byte-range based formatting and links.

  Annotations reference byte offsets into the node's text content,
  enabling precise identification of formatted regions.
  """

  @typedoc "Inline text annotation — byte-range based formatting and links."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          kind: Xberg.AnnotationKind.t()
        }

  defstruct start: 0,
            end: 0,
            kind: :bold
end
