# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f7e7d8e6d809d170f1c4f516fdde5b963a407e17df91ae5ee295b3cd74d17989
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.TranslationConfig do
  @moduledoc "Configuration for the translation post-processor."

  @typedoc "Configuration for the translation post-processor."
  @type t :: %__MODULE__{
          target_lang: String.t() | nil,
          source_lang: String.t() | nil,
          preserve_markup: boolean(),
          llm: Xberg.LlmConfig.t()
        }

  defstruct target_lang: nil,
            source_lang: nil,
            preserve_markup: false,
            llm: nil
end
