# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9a243ef04b77524deab8e158beccce7f16ef5639b770f016fd1a29e7e4d6ef45
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  @typedoc "Year range for bibliographic metadata."
  @type t :: %__MODULE__{
          min: non_neg_integer() | nil,
          max: non_neg_integer() | nil,
          years: [non_neg_integer()]
        }

  defstruct min: nil,
            max: nil,
            years: []
end
