<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e7f6059ce31ffe9667169e53dd96e52879009c68ad4560fbe329975149341f2a
// To regenerate: alef generate
// To verify freshness: alef verify
declare(strict_types=1);

namespace Xberg;

/**
 * Per-category running counter for `RedactionStrategy.TokenReplace`.
 */
final class TokenCounter
{
    /**
     * Create a fresh counter with no previous state.
     */
    public static function new(): TokenCounter
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
