// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:91d0352dd37da237b2bc1cea6055017b6efc42ab301b6c78eebc1feb662aaf27
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A cache read or write operation failed.
/// </summary>
public class CacheException : XbergErrorException {
  public CacheException(string message) : base(message) {}

  public CacheException(string message, Exception innerException)
      : base(message, innerException) {}
}
