// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4b989eb8184911cb8443c6a204b6f228c7af90ca9d60081f485f4f199c3e914a
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// Discriminates the shape of a `CodeDataNode`.
///
/// Purpose-built mirror of `tree_sitter_language_pack.DataNodeKind` — kept as
/// an xberg-owned type so binding generators never need to resolve the upstream
/// crate's types across FFI/language boundaries.
/// </summary>
[JsonConverter(typeof(CodeDataNodeKindJsonConverter))]
public enum CodeDataNodeKind {
  /// <summary>
  /// A key/value pair or mapping (JSON/TOML/properties/YAML/HCL/CUE/KDL pair,
  /// or a wrapper "object"/"mapping" container).
  /// </summary>
  [JsonPropertyName("key_value")] KeyValue,
  /// <summary>
  /// An XML element with a tag name in `key` and attributes in `attributes`.
  /// </summary>
  [JsonPropertyName("element")] Element,
  /// <summary>
  /// A positional sequence item (JSON array element, YAML block sequence item,
  /// CSV/PSV row or cell).
  /// </summary>
  [JsonPropertyName("sequence")] Sequence,
}

/// <summary>
/// Custom JSON converter for <see cref="CodeDataNodeKind"/> that respects
/// explicit variant names.
/// </summary>
internal sealed class CodeDataNodeKindJsonConverter
    : JsonConverter<CodeDataNodeKind> {
  public override CodeDataNodeKind Read(ref Utf8JsonReader reader,
                                        Type typeToConvert,
                                        JsonSerializerOptions options) {
    var value = reader.GetString();
    return value switch { "key_value" => CodeDataNodeKind.KeyValue,
                          "element" => CodeDataNodeKind.Element,
                          "sequence" => CodeDataNodeKind.Sequence,
                          _ => throw new JsonException(
                              $"Unknown CodeDataNodeKind value: {value}") };
  }

  public override void Write(Utf8JsonWriter writer, CodeDataNodeKind value,
                             JsonSerializerOptions options) {
    var str = value switch { CodeDataNodeKind.KeyValue => "key_value",
                             CodeDataNodeKind.Element => "element",
                             CodeDataNodeKind.Sequence => "sequence",
                             _ => throw new JsonException(
                                 $"Unknown CodeDataNodeKind value: {value}") };
    writer.WriteStringValue(str);
  }
}
