// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ffff21513388b05cd5795c43c7e16130e74ee5ce39beae42032c0289f860ff25
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The preset's declared `id` does not match its file-system location.
/// </summary>
public class IdMismatchException : LoadErrorException {
  public IdMismatchException(string message) : base(message) {}

  public IdMismatchException(string message, Exception innerException)
      : base(message, innerException) {}
}
