// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:42ab0052f7c311c35c14cff3f3be3080fdf7c3dd2ca9f934638e462e2ae7a0db
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while loading or validating a preset file.
/// </summary>
public class LoadErrorException : XbergException {
  public LoadErrorException(string message) : base(message) {}

  public LoadErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
