// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:121d4eb493eef590dc59887e13c2f1b8a93bf8f3bd148145d71cddf2da028a62
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A required optional system dependency (e.g. `tesseract`) was not found.
/// </summary>
public class MissingDependencyException : XbergErrorException {
  public MissingDependencyException(string message) : base(message) {}

  public MissingDependencyException(string message, Exception innerException)
      : base(message, innerException) {}
}
