// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ea95c470b52b21c5820e831de7060caedfd05573c8d430e451ccbc0a33854bfc
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : XbergErrorException {
  public OcrException(string message) : base(message) {}

  public OcrException(string message, Exception innerException)
      : base(message, innerException) {}
}
