// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:331fd61d45208919394e15e22a3bfab1b3726681b2602d1e76ac323e0518a352
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A catch-all for uncommon errors that do not fit another variant.
/// </summary>
public class OtherException : XbergErrorException {
  public OtherException(string message) : base(message) {}

  public OtherException(string message, Exception innerException)
      : base(message, innerException) {}
}
