// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0440ae0884dce7f391d69180cbc1f6fa1e3717946a4c01ceeea7879f3f660a97
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Document parsing failed (e.g. corrupt file, unsupported format feature).
/// </summary>
public class ParsingException : XbergErrorException {
  public ParsingException(string message) : base(message) {}

  public ParsingException(string message, Exception innerException)
      : base(message, innerException) {}
}
