// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:59f44ba122d694a9b8de94a0b87b93abc6b107417e953568efbf449d9252e70f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A registered plugin returned an error during extraction.
/// </summary>
public class PluginException : XbergErrorException {
  public PluginException(string message) : base(message) {}

  public PluginException(string message, Exception innerException)
      : base(message, innerException) {}
}
