// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ae176ded4fb2d8c1c2ad750ef862d84e0d1f390b6a0f38800fd62e3c6e452e6f
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// Classification of a detected layout region that warrants VLM extraction.
/// </summary>
[JsonConverter(typeof(RegionKindJsonConverter))]
public enum RegionKind {
  /// <summary>
  /// A figure, diagram, chart, or image region.
  /// </summary>
  [JsonPropertyName("Figure")] Figure,
  /// <summary>
  /// A densely formatted or complex table.
  /// </summary>
  [JsonPropertyName("DenseTable")] DenseTable,
  /// <summary>
  /// A region with complex or mixed layout.
  /// </summary>
  [JsonPropertyName("ComplexLayout")] ComplexLayout,
  /// <summary>
  /// A standalone image to caption.
  /// </summary>
  [JsonPropertyName("Caption")] Caption,
}

/// <summary>
/// Custom JSON converter for <see cref="RegionKind"/> that respects explicit
/// variant names.
/// </summary>
internal sealed class RegionKindJsonConverter : JsonConverter<RegionKind> {
  public override RegionKind Read(ref Utf8JsonReader reader, Type typeToConvert,
                                  JsonSerializerOptions options) {
    var value = reader.GetString();
    return value switch {
      "Figure" => RegionKind.Figure, "DenseTable" => RegionKind.DenseTable,
      "ComplexLayout" => RegionKind.ComplexLayout,
      "Caption" => RegionKind.Caption,
      _ => throw new JsonException($"Unknown RegionKind value: {value}")
    };
  }

  public override void Write(Utf8JsonWriter writer, RegionKind value,
                             JsonSerializerOptions options) {
    var str = value switch {
      RegionKind.Figure => "Figure", RegionKind.DenseTable => "DenseTable",
      RegionKind.ComplexLayout => "ComplexLayout",
      RegionKind.Caption => "Caption",
      _ => throw new JsonException($"Unknown RegionKind value: {value}")
    };
    writer.WriteStringValue(str);
  }
}
