// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0885dbbe6946d5356df5ae554d0dec9fbac3cc6c7b83d1cb63936d735a171f61
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A custom schema override was supplied but is not a JSON object.
/// </summary>
public class SchemaNotObjectException : ResolveErrorException {
  public SchemaNotObjectException(string message) : base(message) {}

  public SchemaNotObjectException(string message, Exception innerException)
      : base(message, innerException) {}
}
