// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c5b6be6460628c4dec1474a07ad629dcc3144281f343ff6c81ede9487da214f6
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A security policy was violated (e.g. zip bomb, oversized archive).
/// </summary>
public class SecurityException : XbergErrorException {
  public SecurityException(string message) : base(message) {}

  public SecurityException(string message, Exception innerException)
      : base(message, innerException) {}
}
