// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5b2a8875df3e227718f24996f36f481b9f87f89131ad16ddbec73009731ed667
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Invalid configuration or input parameters were supplied.
/// </summary>
public class ValidationException : XbergErrorException {
  public ValidationException(string message) : base(message) {}

  public ValidationException(string message, Exception innerException)
      : base(message, innerException) {}
}
