// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6af535c5025d3832244d3f549f925993ddd2c4f11b21a3fb2af7d40bdf525499
// To regenerate: alef generate
// To verify freshness: alef verify

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: tokenizer_backend_management.</summary>
    public class TokenizerBackendManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_TokenizerBackendsClear()
        {
            // Clear all tokenizer backends and verify list is empty
            var exception = Record.Exception(() => XbergConverter.ClearTokenizerBackends());
            Assert.Null(exception);
        }

        [Fact]
        public void Test_TokenizerBackendsList()
        {
            // List all registered tokenizer backends
            var result = XbergConverter.ListTokenizerBackends();
            Assert.NotNull(result);

        }


    }
}
