# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:21c38d2f9017969abf62f3824ae532b4cb1489b5db756f8ee2075a78077faf35
# To regenerate: alef generate
# To verify freshness: alef verify

# frozen_string_literal: true

require "mkmf"
require "rb_sys/mkmf"

default_profile = ENV.fetch("CARGO_PROFILE", "release")

create_rust_makefile("xberg_rb") do |config|
  config.profile = default_profile.to_sym
  # extconf.rb and Cargo.toml are siblings under ext/xberg_rb/native/; rb_sys interprets
  # ext_dir relative to extconf.rb, so "." finds the sibling Cargo.toml. "native" would
  # resolve to native/native/Cargo.toml and break `gem install` on end-user machines.
  config.ext_dir = "."
end
