# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4ba574925dedcf010c8d76dfcc0232e9375c2166fafbc154e97662a15e0e929e
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: extract."""

from pathlib import Path

import pytest
from xberg import ExtractInput, ExtractInputKind, ExtractionConfig, FileExtractionConfig, extract


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


@pytest.mark.asyncio
async def test_extract_bytes_input() -> None:
    """extract bytes input from PDF document."""
    input = ExtractInput(
        bytes=Path("pdf/fake_memo.pdf").read_bytes(),
        filename="fake_memo.pdf",
        kind=ExtractInputKind("bytes"),
        mime_type="application/pdf",
    )

    result = await extract(input)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()
    assert len(result.results[0].content) >= 50


@pytest.mark.asyncio
async def test_extract_bytes_input_empty_mime() -> None:
    """extract bytes input with empty MIME type."""
    with pytest.raises(Exception):
        input = ExtractInput(
            bytes=Path("text/plain.txt").read_bytes(),
            config=FileExtractionConfig(),
            filename="plain.txt",
            kind=ExtractInputKind("bytes"),
            mime_type="",
        )
        config = ExtractionConfig()
        await extract(input, config)


@pytest.mark.asyncio
async def test_extract_bytes_input_invalid_mime() -> None:
    """extract bytes input with unsupported MIME type."""
    with pytest.raises(Exception):
        input = ExtractInput(
            bytes=Path("text/plain.txt").read_bytes(),
            config=FileExtractionConfig(),
            filename="plain.txt",
            kind=ExtractInputKind("bytes"),
            mime_type="application/x-nonexistent",
        )
        config = ExtractionConfig()
        await extract(input, config)
