# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba7a031f41f890c7fe1429b2b78cbae019c2d5941263b860194a56e97e63b3ed
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: batch."""

import json
import os
from pathlib import Path

import pytest
from xberg import ExtractInput, ExtractInputKind, extract_batch


@pytest.mark.asyncio
async def test_extract_batch_bytes_happy() -> None:
    """extract_batch: happy path with mixed inputs."""
    inputs = [
        ExtractInput(
            bytes=[72, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 33],
            kind=ExtractInputKind("bytes"),
            mime_type="text/plain",
        ),
        ExtractInput(bytes=Path("html/html.html").read_bytes(), kind=ExtractInputKind("bytes"), mime_type="text/html"),
    ]

    result = await extract_batch(inputs)
    assert len(result.results) >= 1


@pytest.mark.asyncio
async def test_extract_batch_bytes_invalid_mime() -> None:
    """extract_batch with invalid bytes MIME type."""
    inputs = [
        ExtractInput(
            bytes=[72, 101, 108, 108, 111], kind=ExtractInputKind("bytes"), mime_type="application/x-nonexistent"
        )
    ]

    result = await extract_batch(inputs)
    assert result is not None


@pytest.mark.asyncio
async def test_extract_batch_bytes_mixed_format() -> None:
    """extract_batch: handles unsupported MIME gracefully."""
    inputs = [
        ExtractInput(
            bytes=[80, 68, 70, 32, 112, 108, 97, 99, 101, 104, 111, 108, 100, 101, 114],
            kind=ExtractInputKind("bytes"),
            mime_type="application/x-unknown",
        )
    ]

    result = await extract_batch(inputs)
    assert result is not None


@pytest.mark.asyncio
async def test_extract_batch_bytes_unsupported_mime() -> None:
    """extract_batch with unsupported bytes MIME type."""
    inputs = [ExtractInput(bytes=[100, 97, 116, 97], kind=ExtractInputKind("bytes"), mime_type="application/x-unknown")]

    result = await extract_batch(inputs)
    assert result is not None


@pytest.mark.asyncio
async def test_extract_batch_empty_inputs() -> None:
    """extract_batch: empty batch."""
    inputs = []

    result = await extract_batch(inputs)
    assert len(result.results) == 0


@pytest.mark.asyncio
async def test_extract_batch_uri_all_missing() -> None:
    """extract_batch with missing URI inputs."""
    inputs = [
        ExtractInput(kind=ExtractInputKind("uri"), uri="/nonexistent/a.pdf"),
        ExtractInput(kind=ExtractInputKind("uri"), uri="/nonexistent/b.txt"),
    ]

    result = await extract_batch(inputs)
    assert result.summary.results == 0
    assert result.summary.errors == 2


@pytest.mark.asyncio
async def test_extract_batch_uri_basic() -> None:
    """extract_batch over URI inputs."""
    inputs_mock_base_url = os.environ["MOCK_SERVER_URL"] + "/fixtures/extract_batch_uri_basic"
    inputs_json = '[{"kind":"uri","uri":"$mock_url/pdf/fake_memo.pdf"},{"kind":"uri","uri":"$mock_url/text/fake_text.txt"}]'.replace(
        "$mock_url", inputs_mock_base_url
    )
    inputs_data = json.loads(inputs_json)
    inputs = [
        ExtractInput(kind=ExtractInputKind("uri"), uri=inputs_data[0]["uri"]),
        ExtractInput(kind=ExtractInputKind("uri"), uri=inputs_data[1]["uri"]),
    ]

    result = await extract_batch(inputs)
    assert len(result.results) >= 2


@pytest.mark.asyncio
async def test_extract_batch_uri_not_found() -> None:
    """extract_batch with missing URI input."""
    inputs = [ExtractInput(kind=ExtractInputKind("uri"), uri="/nonexistent/a.pdf")]

    result = await extract_batch(inputs)
    assert result.summary.results == 0
    assert result.summary.errors == 1


@pytest.mark.asyncio
async def test_extract_batch_uri_partial_failure() -> None:
    """extract_batch with one valid URI input and one that downloads to an unparseable document."""
    inputs_mock_base_url = os.environ["MOCK_SERVER_URL"] + "/fixtures/extract_batch_uri_partial_failure"
    inputs_json = '[{"kind":"uri","uri":"$mock_url/text/plain.txt"},{"kind":"uri","uri":"$mock_url/pdf/corrupt_truncated.pdf"}]'.replace(
        "$mock_url", inputs_mock_base_url
    )
    inputs_data = json.loads(inputs_json)
    inputs = [
        ExtractInput(kind=ExtractInputKind("uri"), uri=inputs_data[0]["uri"]),
        ExtractInput(kind=ExtractInputKind("uri"), uri=inputs_data[1]["uri"]),
    ]

    result = await extract_batch(inputs)
    assert result.summary.results == 1
    assert result.summary.errors == 1
