# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:27614cb5715de005c4e07ff415bad277d3eaf238917deb0e4f61cdba4e14b991
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: post_processor_management."""

from xberg import clear_post_processors, list_post_processors


def test_post_processors_clear() -> None:
    """Clear all post-processors and verify list is empty."""
    clear_post_processors()


def test_post_processors_list() -> None:
    """List all registered post-processors."""
    result = list_post_processors()
    assert result is not None
