# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6cb35cd90f095c2bf886d317d7af0b830a2cd6a0b9a027a4b5a08c913f980c84
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: reranker_backend_management."""

from xberg import clear_reranker_backends, list_reranker_backends


def test_clear_reranker_backends() -> None:
    """Clear all reranker backends and verify list is empty."""
    clear_reranker_backends()


def test_list_reranker_backends() -> None:
    """List all registered reranker backends."""
    result = list_reranker_backends()
    assert result is not None
