# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8973aef19be517c0a89ed83149e8418faf42c4ac06ffbc982e256f7ec4d4aa4f
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: registry."""

from xberg import list_embedding_backends, list_ocr_backends, list_post_processors, list_renderers, list_validators


def test_list_embedding_backends() -> None:
    """List embedding backends."""
    result = list_embedding_backends()
    assert result is not None


def test_list_ocr_backends() -> None:
    """List OCR backends."""
    result = list_ocr_backends()
    assert result is not None


def test_list_post_processors() -> None:
    """List post-processors."""
    result = list_post_processors()
    assert result is not None


def test_list_renderers() -> None:
    """List renderers."""
    result = list_renderers()
    assert result is not None


def test_list_validators() -> None:
    """List validators."""
    result = list_validators()
    assert result is not None
