# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a8a56e658b4bc27c0b0ed0612f68f5e51308cec8090bc4f950f694ce481c5bb8
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Attributes do
  @moduledoc """
  Element attributes in Djot.

  Represents the attributes attached to elements using {.class #id key="value"} syntax.
  """

  @typedoc "Element attributes in Djot."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          classes: [String.t()],
          key_values: [Xberg.KeyValueAttribute.t()]
        }

  defstruct id: nil,
            classes: [],
            key_values: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
