# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1b160a5e0d121d84d3a87d21c5a81dc0f8a87a1398e910ab738ceeab63017518
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.BBox do
  @moduledoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."

  @typedoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."
  @type t :: %__MODULE__{
          x1: float(),
          y1: float(),
          x2: float(),
          y2: float()
        }

  defstruct x1: 0.0,
            y1: 0.0,
            x2: 0.0,
            y2: 0.0
end
