# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:82bfba6fd6ff9ee764c6cf97c02d07be71f69844bd7f2a72239e1cbff7298012
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.CacheStats do
  @moduledoc "Aggregate statistics for a xberg cache directory."

  @typedoc "Aggregate statistics for a xberg cache directory."
  @type t :: %__MODULE__{
          total_files: non_neg_integer(),
          total_size_mb: float(),
          available_space_mb: float(),
          oldest_file_age_days: float(),
          newest_file_age_days: float()
        }

  defstruct total_files: 0,
            total_size_mb: 0.0,
            available_space_mb: 0.0,
            oldest_file_age_days: 0.0,
            newest_file_age_days: 0.0
end
