# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2441182cea95941220d34f67a57b8526fde857f7c1989e4a9427646f51c81f7c
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  @typedoc "JATS contributor with role."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          role: String.t() | nil
        }

  defstruct name: nil,
            role: nil
end
