# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a7be3536d9442e2e2e6dc37567ab834fa4feb2a06b9ef948bbd47c74ce323cc8
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  @typedoc "dBASE field information."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          field_type: String.t() | nil
        }

  defstruct name: nil,
            field_type: nil
end
