# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4fda6adb6e7f2a303e8bfdc5bfca65ede7fcc4b1b5de2a5f0ecf3d140e1a55dc
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DeepseekOcrBackendOptions do
  @moduledoc "Runtime options accepted by the `candle-deepseek-ocr` backend."

  @typedoc "Runtime options accepted by the `candle-deepseek-ocr` backend."
  @type t :: %__MODULE__{
          model_path: String.t() | nil,
          device: Xberg.CandleDevicePreference.t() | nil,
          version: non_neg_integer() | nil
        }

  defstruct model_path: nil,
            device: nil,
            version: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
