# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9e30100b3518de0ad001dae8b26030daf68af2e9f5731a4fe06b188b88cd8527
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DiffHunk do
  @moduledoc "A single contiguous hunk in a unified diff."

  @typedoc "A single contiguous hunk in a unified diff."
  @type t :: %__MODULE__{
          from_line: non_neg_integer(),
          from_count: non_neg_integer(),
          to_line: non_neg_integer(),
          to_count: non_neg_integer(),
          lines: [Xberg.DiffLine.t()]
        }

  defstruct from_line: 0,
            from_count: 0,
            to_line: 0,
            to_count: 0,
            lines: []
end
