# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c13935a95ecb6de5fb90f25e2cb19179f81717ed84b0cd1e954fb965365ca10c
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DjotContent do
  @moduledoc """
  Comprehensive Djot document structure with semantic preservation.

  This type captures the full richness of Djot markup, including:
  - Block-level structures (headings, lists, blockquotes, code blocks, etc.)
  - Inline formatting (emphasis, strong, highlight, subscript, superscript, etc.)
  - Attributes (classes, IDs, key-value pairs)
  - Links, images, footnotes
  - Math expressions (inline and display)
  - Tables with full structure

  Available when the `djot` feature is enabled.
  """

  @typedoc "Comprehensive Djot document structure with semantic preservation."
  @type t :: %__MODULE__{
          plain_text: String.t() | nil,
          blocks: [Xberg.FormattedBlock.t()],
          metadata: Xberg.Metadata.t(),
          tables: [Xberg.Table.t()],
          images: [Xberg.DjotImage.t()],
          links: [Xberg.DjotLink.t()],
          footnotes: [Xberg.Footnote.t()],
          attributes: [Xberg.DjotAttributeGroup.t()]
        }

  defstruct plain_text: nil,
            blocks: [],
            metadata: nil,
            tables: [],
            images: [],
            links: [],
            footnotes: [],
            attributes: []
end
