# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a434411358e5fd235f979de8abe6e122436075a925b3c14d4f3cb0dd9832c6d8
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DjotImage do
  @moduledoc "Image element in Djot."

  @typedoc "Image element in Djot."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          attributes: Xberg.Attributes.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            attributes: nil
end
