# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6ac934e2e399e3cd14b98859fdec35ea12f689e7b9013d10d4b57b038c2f3998
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DocumentSummary do
  @moduledoc "Summary of an extracted document."

  @typedoc "Summary of an extracted document."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          strategy: Xberg.SummaryStrategy.t(),
          token_count: non_neg_integer() | nil
        }

  defstruct text: nil,
            strategy: :extractive,
            token_count: nil
end
