# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bfa0db2c6986234d44a0765e003b53d6ff1f9634541cdc3deb8174b3cc4ce080
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ElementMetadata do
  @moduledoc "Metadata for a semantic element."

  @typedoc "Metadata for a semantic element."
  @type t :: %__MODULE__{
          page_number: non_neg_integer() | nil,
          filename: String.t() | nil,
          coordinates: Xberg.BoundingBox.t() | nil,
          element_index: non_neg_integer() | nil,
          additional: map()
        }

  defstruct page_number: nil,
            filename: nil,
            coordinates: nil,
            element_index: nil,
            additional: %{}
end
