# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ccd977cc4db6c74fe994aea34dfb3a203d77886fe69c1d1c0c826c2ab15210a5
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.EmailAttachment do
  @moduledoc """
  Email attachment representation.

  Contains metadata and optionally the content of an email attachment.
  """

  @typedoc "Email attachment representation."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          filename: String.t() | nil,
          mime_type: String.t() | nil,
          size: non_neg_integer() | nil,
          is_image: boolean(),
          data: binary() | nil
        }

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
