# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:25ff06fc02c72b0555235a0c0ebd0ce9da8c5f6ef2069307bb1899988fdecc54
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  @typedoc "Embedded file descriptor extracted from the PDF name tree."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          data: binary(),
          compressed_size: non_neg_integer(),
          mime_type: String.t() | nil
        }

  defstruct name: nil,
            data: <<>>,
            compressed_size: 0,
            mime_type: nil
end
