# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4f1fadc59e837b533ccb5f6393fbc4f98ac252a7d835252babb606144a4298fb
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.EmbeddedDiff do
  @moduledoc "Diff for a single embedded archive entry that appears in both results."

  @typedoc "Diff for a single embedded archive entry that appears in both results."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          diff: Xberg.ExtractionDiff.t()
        }

  defstruct path: nil,
            diff: nil
end
