# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b939102c897f581803b5f55c602e137327094a768ffc89ac5ddbd01ab56ef120
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ExtractionConfidence do
  @moduledoc """
  Combined confidence on `[0, 1]`.

  When OCR did not run, the `ocr_aggregate` weight folds into `text_coverage`
  so the weighted sum still totals 1.0.
  """

  @typedoc "Combined confidence on `[0, 1]`."
  @type t :: %__MODULE__{
          text_coverage: float(),
          ocr_aggregate: float() | nil,
          schema_compliance: Xberg.SchemaCompliance.t(),
          combined: float()
        }

  defstruct text_coverage: 0.0,
            ocr_aggregate: nil,
            schema_compliance: :all_valid,
            combined: 0.0
end
