# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:92d7165fc4918f20a2ad44bea7e81677c3ee05844d1c558b0da6b786f08a5c09
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ExtractionMethod do
  @moduledoc "How the extracted text was produced."

  @typedoc "How the extracted text was produced."
  @type t :: :native | :ocr | :mixed

  @native :native
  @ocr :ocr
  @mixed :mixed

  @doc "Text extracted directly from the document's native format (no OCR)."
  @spec native() :: t()
  def native, do: @native
  @doc "All text was obtained via OCR (e.g. scanned image-only PDF)."
  @spec ocr() :: t()
  def ocr, do: @ocr
  @doc "Text came from a combination of native extraction and OCR."
  @spec mixed() :: t()
  def mixed, do: @mixed

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:native), do: "native"
  def wire_value(:ocr), do: "ocr"
  def wire_value(:mixed), do: "mixed"
end
