# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cad201f32217b70c41c4fdce8c628b7518568a7fb4753467cb6a4fe7e8d34ff6
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ExtractInputKind do
  @moduledoc "Source kind for [`ExtractInput`]."

  @typedoc "Source kind for [`ExtractInput`]."
  @type t :: :bytes | :uri

  @bytes :bytes
  @uri :uri

  @doc "Raw in-memory bytes."
  @spec bytes() :: t()
  def bytes, do: @bytes
  @doc "A filesystem path, `file://` URI, or HTTP(S) URL."
  @spec uri() :: t()
  def uri, do: @uri

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:bytes), do: "bytes"
  def wire_value(:uri), do: "uri"
end
