# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6bb2273e9a2ae91a9c29b1aaa0554991d58d5b7989c3108c1731d03353e4de37
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.FootnoteConfig do
  @moduledoc "Configuration for markdown footnote and citation parsing."

  @typedoc "Configuration for markdown footnote and citation parsing."
  @type t :: %__MODULE__{
          parse_citations: boolean()
        }

  defstruct parse_citations: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
