# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a721992bb83dc6618ca8e7acef792efb2c2a8459f5af5cc77b2d0c45e0c6d3dc
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.FormattedBlock do
  @moduledoc """
  Block-level element in a Djot document.

  Represents structural elements like headings, paragraphs, lists, code blocks, etc.
  """

  @typedoc "Block-level element in a Djot document."
  @type t :: %__MODULE__{
          block_type: Xberg.BlockType.t(),
          level: non_neg_integer() | nil,
          inline_content: [Xberg.InlineElement.t()],
          attributes: Xberg.Attributes.t() | nil,
          language: String.t() | nil,
          code: String.t() | nil,
          children: [Xberg.FormattedBlock.t()]
        }

  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            attributes: nil,
            language: nil,
            code: nil,
            children: []
end
