# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7ba559bdfd9c3995e517f987cb579e6ac7f82d2bc65d808b69a8781aeae1f945
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.GeoJsonExtractionConfig do
  @moduledoc """
  Configuration for GeoJSON extraction.

  GeoJSON coordinates can dominate extraction output and duplicate large geometry
  payloads in rendered content and metadata. The default therefore emits a bounded
  aggregate summary. Set [`Self::include_full_coordinates`] only when callers need
  every coordinate in the extracted text and accept output proportional to the input.
  """

  @typedoc "Configuration for GeoJSON extraction."
  @type t :: %__MODULE__{
          include_full_coordinates: boolean()
        }

  defstruct include_full_coordinates: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
