# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c8730c752f7d9853124f14f9f5ba0cf768bb3303dafaccee6818d9ded6eb17e6
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.GlmOcrTaskKind do
  @moduledoc "Task accepted by `candle-glm-ocr` backend options."

  @typedoc "Task accepted by `candle-glm-ocr` backend options."
  @type t :: :ocr | :table | :formula | :chart | :caption

  @ocr :ocr
  @table :table
  @formula :formula
  @chart :chart
  @caption :caption

  @spec ocr() :: t()
  def ocr, do: @ocr
  @spec table() :: t()
  def table, do: @table
  @spec formula() :: t()
  def formula, do: @formula
  @spec chart() :: t()
  def chart, do: @chart
  @spec caption() :: t()
  def caption, do: @caption

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:ocr), do: "ocr"
  def wire_value(:table), do: "table"
  def wire_value(:formula), do: "formula"
  def wire_value(:chart), do: "chart"
  def wire_value(:caption), do: "caption"
end
