# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b1071e955a59806fbdd6b3ab1aa64311c1906ed52d1864d173f4c7cc71d3a575
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.HierarchicalBlock do
  @moduledoc false

  @type t :: %__MODULE__{
          text: String.t() | nil,
          font_size: float(),
          level: String.t() | nil,
          bbox: Xberg.HierarchicalBoundingBox.t() | nil
        }

  defstruct text: nil,
            font_size: 0.0,
            level: nil,
            bbox: nil
end
