# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:04261d9c399349718738ef24e21cfc41a349df9928dea4c80f859e33f41b8cf7
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ImageDpi do
  @moduledoc "Horizontal and vertical image resolution in dots per inch."

  @typedoc "Horizontal and vertical image resolution in dots per inch."
  @type t :: %__MODULE__{
          horizontal: float(),
          vertical: float()
        }

  defstruct horizontal: 0.0,
            vertical: 0.0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
