# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c6546eb4ed5bee18927f171fc4a04c10d361847afdbc9a6dac61e46e51f38026
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ImageDimensions do
  @moduledoc "Image dimensions in pixels."

  @typedoc "Image dimensions in pixels."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer()
        }

  defstruct width: 0,
            height: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
