# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bd3df40c042f74f537b1a3fc58de572e5bd7f0b9dad30252f15ccfca906fb7f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  @typedoc "Image element metadata."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          dimensions: Xberg.ImageDimensions.t() | nil,
          image_type: Xberg.ImageType.t(),
          attributes: [Xberg.KeyValueAttribute.t()]
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: []
end
