# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5bd244166e79a001244d31cd681adcf760da0134621dfcf90a794871597dd4de
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ImagePreprocessingMetadata do
  @moduledoc false

  @type t :: %__MODULE__{
          original_dimensions: Xberg.PixelDimensions.t(),
          original_dpi: Xberg.ImageDpi.t(),
          target_dpi: integer(),
          scale_factor: float(),
          auto_adjusted: boolean(),
          final_dpi: integer(),
          new_dimensions: Xberg.PixelDimensions.t() | nil,
          resample_method: String.t() | nil,
          dimension_clamped: boolean(),
          calculated_dpi: integer() | nil,
          skipped_resize: boolean(),
          resize_error: String.t() | nil
        }

  defstruct original_dimensions: nil,
            original_dpi: nil,
            target_dpi: 0,
            scale_factor: 0.0,
            auto_adjusted: false,
            final_dpi: 0,
            new_dimensions: nil,
            resample_method: nil,
            dimension_clamped: false,
            calculated_dpi: nil,
            skipped_resize: false,
            resize_error: nil
end
