# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:81d26626a9d13e278de154491a9f9bd7a9d60bc19a4028b3c72255f577e2798e
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.InlineElement do
  @moduledoc """
  Inline element within a block.

  Represents text with formatting, links, images, etc.
  """

  @typedoc "Inline element within a block."
  @type t :: %__MODULE__{
          element_type: Xberg.InlineType.t(),
          content: String.t() | nil,
          attributes: Xberg.Attributes.t() | nil,
          metadata: map() | nil
        }

  defstruct element_type: :text,
            content: nil,
            attributes: nil,
            metadata: nil
end
