# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3e5bb9ac295a88992085838e528ba5c970c9ba90ab47ab2972e0dc90edc2034a
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.KeyValueAttribute do
  @moduledoc "A string key-value attribute."

  @typedoc "A string key-value attribute."
  @type t :: %__MODULE__{
          key: String.t() | nil,
          value: String.t() | nil
        }

  defstruct key: nil,
            value: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
