# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1135b4a386139f86a07b0cbfaba268d04d8eb344504ab45e4d51a6e8dd89dd9e
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  @typedoc "Language detection configuration."
  @type t :: %__MODULE__{
          enabled: boolean(),
          min_confidence: float(),
          detect_multiple: boolean()
        }

  defstruct enabled: true,
            min_confidence: 0.8,
            detect_multiple: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
