# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:45f1d67cbfc52106efe47868b7b12d9539fb91635b1f9c38d98114688dc6189f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  @typedoc "A single layout detection result."
  @type t :: %__MODULE__{
          class_name: Xberg.LayoutClass.t(),
          confidence: float(),
          bbox: Xberg.BBox.t()
        }

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
