# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0623369b5e79c55582817be6580feb75e5bac2c4e709eb26f46a5187c4ba9aa9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LinkMetadata do
  @moduledoc "Link element metadata."

  @typedoc "Link element metadata."
  @type t :: %__MODULE__{
          href: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          link_type: Xberg.LinkType.t(),
          rel: [String.t()],
          attributes: [Xberg.KeyValueAttribute.t()]
        }

  defstruct href: nil,
            text: nil,
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
