# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7cc8b39a500e34534aa3151a275417a78b936fba865121f78f911bb34f20bc5b
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LlmRateLimitConfig do
  @moduledoc """
  Per-model rate limiting configuration.

  Mirrors liter-llm's `LlmRateLimitConfig`. Only takes effect when liter-llm's
  `tower` feature is compiled in; otherwise the value round-trips through
  configuration but is not enforced at request time.
  """

  @typedoc "Per-model rate limiting configuration."
  @type t :: %__MODULE__{
          rpm: non_neg_integer() | nil,
          tpm: non_neg_integer() | nil,
          window_seconds: non_neg_integer() | nil
        }

  defstruct rpm: nil,
            tpm: nil,
            window_seconds: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
