# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:51a4792df286ca73c8df30d79810003a154da1ce565469ca589794a0880de9a2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.MimeDetectionPolicy do
  @moduledoc "Selects which evidence is authoritative when Xberg infers a MIME type."

  @typedoc "Selects which evidence is authoritative when Xberg infers a MIME type."
  @type t :: :prefer_content | :trust_extension | :content_only

  @prefer_content :prefer_content
  @trust_extension :trust_extension
  @content_only :content_only

  @doc "Prefer a supported content signature, falling back to the filename extension."
  @spec prefer_content() :: t()
  def prefer_content, do: @prefer_content
  @doc "Trust a supported filename extension without reading content for detection."
  @spec trust_extension() :: t()
  def trust_extension, do: @trust_extension
  @doc "Ignore the filename extension and require content-based detection."
  @spec content_only() :: t()
  def content_only, do: @content_only

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:prefer_content), do: "prefer_content"
  def wire_value(:trust_extension), do: "trust_extension"
  def wire_value(:content_only), do: "content_only"
end
