# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:22063ae642350b0a74d00d0d34daabe4f015bed7e23d0b007dd8cbc9dd42af49
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.MultiVectorEmbedding do
  @moduledoc """
  A ColBERT multi-vector embedding: one row per attention-live token.

  `data` is a flat, row-major buffer of length `num_tokens * dim` — row `i`
  (the embedding for token `i`) occupies `data[i*dim .. (i+1)*dim]`. Flat
  storage keeps the type FFI-friendly across binding boundaries; use
  [`MultiVectorEmbedding::rows`] internally to iterate per-token slices.
  """

  @typedoc "A ColBERT multi-vector embedding: one row per attention-live token."
  @type t :: %__MODULE__{
          num_tokens: non_neg_integer(),
          dim: non_neg_integer(),
          data: [float()]
        }

  defstruct num_tokens: 0,
            dim: 0,
            data: []
end
