# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2d2859d7f5a8356881a2d8e77a2b17e0a97ca9b6a50e5a08af8262193f7132b4
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  @typedoc "Bounding box for an OCR-detected table in pixel coordinates."
  @type t :: %__MODULE__{
          left: non_neg_integer(),
          top: non_neg_integer(),
          right: non_neg_integer(),
          bottom: non_neg_integer()
        }

  defstruct left: 0,
            top: 0,
            right: 0,
            bottom: 0
end
