# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0190b5a012b65c28768268b249dd3c8a40fad499049162e8e02ca0336e0c84ba
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrBackendType do
  @moduledoc "OCR backend types."

  @typedoc "OCR backend types."
  @type t :: :tesseract | :paddle_ocr | :candle | :custom

  @tesseract :tesseract
  @paddle_ocr :paddle_ocr
  @candle :candle
  @custom :custom

  @doc "Tesseract OCR (native Rust binding)"
  @spec tesseract() :: t()
  def tesseract, do: @tesseract
  @doc "PaddleOCR (Python-based, via FFI)"
  @spec paddle_ocr() :: t()
  def paddle_ocr, do: @paddle_ocr
  @doc "Candle-based VLM OCR (TrOCR, PaddleOCR-VL)."
  @spec candle() :: t()
  def candle, do: @candle
  @doc "Name-selected built-in or third-party OCR backend."
  @spec custom() :: t()
  def custom, do: @custom

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:tesseract), do: "Tesseract"
  def wire_value(:paddle_ocr), do: "PaddleOCR"
  def wire_value(:candle), do: "Candle"
  def wire_value(:custom), do: "Custom"
end
