# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b3e9cae6a27519832d56744734b6fe692b19899be90fdb3d2b55741b57883dda
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrPoint do
  @moduledoc "A point in OCR raster pixel coordinates."

  @typedoc "A point in OCR raster pixel coordinates."
  @type t :: %__MODULE__{
          x: non_neg_integer(),
          y: non_neg_integer()
        }

  defstruct x: 0,
            y: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
