# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b40e93a206bc70c3e0b8a92706211c56921ad3ca5491c65f0be767af52ba45cc
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrElementConfig do
  @moduledoc """
  Configuration for OCR element extraction.

  Controls how OCR elements are extracted and filtered.
  """

  @typedoc "Configuration for OCR element extraction."
  @type t :: %__MODULE__{
          include_elements: boolean(),
          min_level: Xberg.OcrElementLevel.t(),
          min_confidence: float(),
          build_hierarchy: boolean()
        }

  defstruct include_elements: false,
            min_level: :line,
            min_confidence: 0.0,
            build_hierarchy: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
