# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c379ab99e5f973170e6ac0636f66551659984415a1b0264fc01efa8f6b183b33
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  @typedoc "Rotation information for an OCR element."
  @type t :: %__MODULE__{
          angle_degrees: float(),
          confidence: float() | nil
        }

  defstruct angle_degrees: 0.0,
            confidence: nil
end
