# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:075e871c5486fa1bfe35b8abbcb957953cb975ef4da34b69e80c176f90b33bc1
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageClassificationConfig do
  @moduledoc "Configuration for the page-classification post-processor."

  @typedoc "Configuration for the page-classification post-processor."
  @type t :: %__MODULE__{
          prompt_template: String.t() | nil,
          labels: [String.t()],
          multi_label: boolean(),
          llm: Xberg.LlmConfig.t()
        }

  defstruct prompt_template: nil,
            labels: [],
            multi_label: false,
            llm: nil
end
