# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:544cb865c117dc8d630982796ed2fa695f250ea32b5e3c4872c887609f6e9c96
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageHierarchy do
  @moduledoc """
  Page hierarchy structure containing heading levels and block information.

  Used when PDF text hierarchy extraction is enabled. Contains hierarchical
  blocks with heading levels (H1-H6) for semantic document structure.
  """

  @typedoc "Page hierarchy structure containing heading levels and block information."
  @type t :: %__MODULE__{
          block_count: non_neg_integer(),
          blocks: [Xberg.HierarchicalBlock.t()]
        }

  defstruct block_count: 0,
            blocks: []
end
