# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:92a5e97d8628027ec2952dd403ab2b2774cb37a217ca3ed673e63a3c9a736bce
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageRange do
  @moduledoc "Page range for a chunk (0-indexed, inclusive)."

  @typedoc "Page range for a chunk (0-indexed, inclusive)."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer()
        }

  defstruct start: 0,
            end: 0
end
