# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f6db3175deb8eb90df58f53fbd2b85db1e498ca80b96ab4232e094fad33dc8f9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PatternMatch do
  @moduledoc "One detected PII span in the input text."

  @typedoc "One detected PII span in the input text."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          category: Xberg.PiiCategory.t(),
          text: String.t() | nil
        }

  defstruct start: 0,
            end: 0,
            category: :email,
            text: nil
end
