# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:953162a5aa734fd15be3a9f95f73ca6c3e751d0af8df5e6177d6f8c8596f81bc
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PdfConfig do
  @moduledoc "PDF-specific configuration."

  @typedoc "PDF-specific configuration."
  @type t :: %__MODULE__{
          extract_images: boolean(),
          extract_tables: boolean(),
          passwords: [String.t()] | nil,
          extract_metadata: boolean(),
          hierarchy: Xberg.HierarchyConfig.t() | nil,
          extract_annotations: boolean(),
          top_margin_fraction: float() | nil,
          bottom_margin_fraction: float() | nil,
          allow_single_column_tables: boolean(),
          ocr_inline_images: boolean(),
          extract_form_fields: boolean(),
          reading_order: boolean(),
          backend: Xberg.PdfBackend.t()
        }

  defstruct extract_images: false,
            extract_tables: true,
            passwords: nil,
            extract_metadata: true,
            hierarchy: nil,
            extract_annotations: false,
            top_margin_fraction: nil,
            bottom_margin_fraction: nil,
            allow_single_column_tables: false,
            ocr_inline_images: false,
            extract_form_fields: true,
            reading_order: false,
            backend: :native

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
