# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:87251dc653df0a96014069828c8a7d237212cf251ffd49bc84f1634c2bebe30c
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PixelDimensions do
  @moduledoc """
  Image preprocessing metadata.

  Tracks the transformations applied to an image during OCR preprocessing,
  including DPI normalization, resizing, and resampling.
  """

  @typedoc "Image preprocessing metadata."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer()
        }

  defstruct width: 0,
            height: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
