# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5a1540bf456bf3ad62ac91fbb7c8fdd9778e51e2b514fe6e4cee688ff4276341
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PostProcessorConfig do
  @moduledoc "Post-processor configuration."

  @typedoc "Post-processor configuration."
  @type t :: %__MODULE__{
          enabled: boolean(),
          enabled_processors: [String.t()] | nil,
          disabled_processors: [String.t()] | nil,
          enabled_set: [String.t()] | nil,
          disabled_set: [String.t()] | nil
        }

  defstruct enabled: true,
            enabled_processors: nil,
            disabled_processors: nil,
            enabled_set: nil,
            disabled_set: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
