# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9105de71fe2b0a091243a0a97d11aecebb67e58947590abe2a5fa2fdb0c892b7
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PresentationHyperlink do
  @moduledoc "A hyperlink discovered in a presentation slide."

  @typedoc "A hyperlink discovered in a presentation slide."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          label: String.t() | nil
        }

  defstruct url: nil,
            label: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
