# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b21cb659c2c76b44aef0fce66e6b80d02187d6b3068398a3d290d8a5eae2268c
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ProcessingWarning do
  @moduledoc """
  A non-fatal warning from a processing pipeline stage.

  Captures errors from optional features that don't prevent extraction
  but may indicate degraded or incomplete results. Inspect these independently
  from `ExtractedDocument::quality_score`, which assesses retained text only.
  """

  @typedoc "A non-fatal warning from a processing pipeline stage."
  @type t :: %__MODULE__{
          source: String.t() | nil,
          message: String.t() | nil
        }

  defstruct source: nil,
            message: nil
end
