# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44a2e2d1592972b053b19433c12dd38942bcc5c327d1feaef1f45419c0c027d9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ProcessingStage do
  @moduledoc """
  Processing stages for post-processors.

  Post-processors are executed in stage order (Early → Middle → Late).
  Use stages to control the order of post-processing operations.
  """

  @typedoc "Processing stages for post-processors."
  @type t :: :early | :middle | :late

  @early :early
  @middle :middle
  @late :late

  @doc "Early stage - foundational processing."
  @spec early() :: t()
  def early, do: @early
  @doc "Middle stage - content transformation."
  @spec middle() :: t()
  def middle, do: @middle
  @doc "Late stage - final enrichment."
  @spec late() :: t()
  def late, do: @late

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:early), do: "Early"
  def wire_value(:middle), do: "Middle"
  def wire_value(:late), do: "Late"
end
