# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c4b0c52387b362fb2ebcfedf046f5c2d05494933fd77a0552ed95e6c5fabd4d9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ProxyConfig do
  @moduledoc "Proxy configuration for HTTP requests."

  @typedoc "Proxy configuration for HTTP requests."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          username: String.t() | nil,
          password: String.t() | nil
        }

  defstruct url: nil,
            username: nil,
            password: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
