# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cff35aac2cf20f4c23944e48f141ceb87961cbd558aa47446b9513c2376907d2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  @typedoc "Outlook PST archive metadata."
  @type t :: %__MODULE__{
          message_count: non_neg_integer()
        }

  defstruct message_count: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
