# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:72976c908abec435d0733fad4e7da2f77ef3c72e9c744e2fe98c861bf29f841e
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.QrCode do
  @moduledoc "One QR code decoded from an extracted image."

  @typedoc "One QR code decoded from an extracted image."
  @type t :: %__MODULE__{
          payload: String.t() | nil,
          confidence: float() | nil,
          bbox: Xberg.QrBoundingBox.t() | nil
        }

  defstruct payload: nil,
            confidence: nil,
            bbox: nil
end
