# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8e76bf8b7a9dced0796ecbf7131d28dac714bd82f8d59e780c74211cdd6c3a84
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.RakeParams do
  @moduledoc "RAKE-specific parameters."

  @typedoc "RAKE-specific parameters."
  @type t :: %__MODULE__{
          min_word_length: non_neg_integer(),
          max_words_per_phrase: non_neg_integer()
        }

  defstruct min_word_length: 1,
            max_words_per_phrase: 3

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
