# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9d039b1e08d9fe697eace3b1a8f9bd18718c18be5c7a75f82a5f688da5bb3e91
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.RedactionConfig do
  @moduledoc "Configuration for the redaction post-processor."

  @typedoc "Configuration for the redaction post-processor."
  @type t :: %__MODULE__{
          categories: [Xberg.PiiCategory.t()],
          strategy: Xberg.RedactionStrategy.t(),
          ner: Xberg.NerConfig.t() | nil,
          preserve_offsets: boolean(),
          custom_terms: [Xberg.RedactionTerm.t()],
          custom_patterns: [Xberg.RedactionPattern.t()]
        }

  defstruct categories: [],
            strategy: :mask,
            ner: nil,
            preserve_offsets: true,
            custom_terms: [],
            custom_patterns: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
