# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:672f0d047f6c3306b137af6f735d96c7d131b0c17a980e22f88337beebb44795
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ReductionLevel do
  @moduledoc "Intensity level for the token-reduction pipeline."

  @typedoc "Intensity level for the token-reduction pipeline."
  @type t :: :off | :light | :moderate | :aggressive | :maximum

  @off :off
  @light :light
  @moderate :moderate
  @aggressive :aggressive
  @maximum :maximum

  @doc "No reduction applied; text is returned as-is."
  @spec off() :: t()
  def off, do: @off
  @doc "Remove only the most common stopwords."
  @spec light() :: t()
  def light, do: @light
  @doc "Balanced stopword removal and redundancy filtering."
  @spec moderate() :: t()
  def moderate, do: @moderate
  @doc "Aggressive filtering; may remove less common content words."
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
  @doc "Maximum compression; prioritizes brevity over completeness."
  @spec maximum() :: t()
  def maximum, do: @maximum

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:off), do: "Off"
  def wire_value(:light), do: "Light"
  def wire_value(:moderate), do: "Moderate"
  def wire_value(:aggressive), do: "Aggressive"
  def wire_value(:maximum), do: "Maximum"
end
