# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7462ef8ee28e987782170b0b069460514f31f6644df20646694383ece1ccb25e
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.RerankedDocument do
  @moduledoc """
  A single document returned by the reranker, with its position in the input and score.

  `index` maps back to the caller's original document list, so metadata arrays
  (e.g. IDs, paths) can be reordered without passing them through the reranker.
  """

  @typedoc "A single document returned by the reranker, with its position in the input and score."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          score: float(),
          document: String.t() | nil
        }

  defstruct index: 0,
            score: 0.0,
            document: nil
end
