# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:05c078ba283ce95e1ae9ef8b8bdc98f9d0b9cc434ae56aee87f439fa59ab4f9d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.RerankerConfig do
  @moduledoc """
  Configuration for the reranking pipeline.

  Controls which model to use, how many results to return, and download/cache
  behavior for local ONNX models.
  """

  @typedoc "Configuration for the reranking pipeline."
  @type t :: %__MODULE__{
          model: Xberg.RerankerModelType.t(),
          top_k: non_neg_integer() | nil,
          batch_size: non_neg_integer(),
          show_download_progress: boolean(),
          cache_dir: String.t() | nil,
          acceleration: Xberg.AccelerationConfig.t() | nil,
          max_rerank_duration_secs: non_neg_integer() | nil
        }

  defstruct model: nil,
            top_k: nil,
            batch_size: 32,
            show_download_progress: false,
            cache_dir: nil,
            acceleration: nil,
            max_rerank_duration_secs: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
