# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:55509fb3629ba36f0df7f7a076062b107e1bb9e805676ce48032a3428a7efad8
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.RevisionKind do
  @moduledoc "Semantic classification of a tracked change."

  @typedoc "Semantic classification of a tracked change."
  @type t :: :insertion | :deletion | :format_change | :comment

  @insertion :insertion
  @deletion :deletion
  @format_change :format_change
  @comment :comment

  @doc "Text or content was inserted."
  @spec insertion() :: t()
  def insertion, do: @insertion
  @doc "Text or content was deleted."
  @spec deletion() :: t()
  def deletion, do: @deletion
  @doc "Run-level formatting (font, size, colour, …) was changed."
  @spec format_change() :: t()
  def format_change, do: @format_change
  @doc "A reviewer comment or annotation."
  @spec comment() :: t()
  def comment, do: @comment

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:insertion), do: "insertion"
  def wire_value(:deletion), do: "deletion"
  def wire_value(:format_change), do: "format_change"
  def wire_value(:comment), do: "comment"
end
