# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:96b904d2c8182108f38b28e9ad2f8a1b1f96abda6599309f7556f3c0e176a020
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  @typedoc "Structured data (Schema.org, microdata, RDFa) block."
  @type t :: %__MODULE__{
          data_type: Xberg.StructuredDataType.t(),
          raw_json: String.t() | nil,
          schema_type: String.t() | nil
        }

  defstruct data_type: :json_ld,
            raw_json: nil,
            schema_type: nil
end
