# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b197a70adc35872ad0d89a7b8cd13d722bfd8d0714ca4601ef192c4a3be687c1
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.SummarizationConfig do
  @moduledoc "Configuration for the summarisation post-processor."

  @typedoc "Configuration for the summarisation post-processor."
  @type t :: %__MODULE__{
          strategy: Xberg.SummaryStrategy.t(),
          max_tokens: non_neg_integer() | nil,
          llm: Xberg.LlmConfig.t() | nil
        }

  defstruct strategy: :extractive,
            max_tokens: nil,
            llm: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
