# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:806ceb31ad9b4b2835a6c6098615563bc5192e07642d2db52e8e0249644fffd8
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.TextMetadata do
  @moduledoc """
  Text/Markdown metadata.

  Extracted from plain text and Markdown files. Includes word counts and,
  for Markdown, structural elements like headers and links.
  """

  @typedoc "Text/Markdown metadata."
  @type t :: %__MODULE__{
          line_count: non_neg_integer(),
          word_count: non_neg_integer(),
          character_count: non_neg_integer(),
          headers: [String.t()] | nil,
          links: [Xberg.MarkdownLink.t()] | nil,
          code_blocks: [Xberg.MarkdownCodeBlock.t()] | nil
        }

  defstruct line_count: 0,
            word_count: 0,
            character_count: 0,
            headers: nil,
            links: nil,
            code_blocks: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
