# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4ec4abb360b758288e666083fe8342c730746d4aaa5ce24f4623153972aafd4c
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.TierStrategy do
  @moduledoc "Controls which conversion tier is used."

  @typedoc "Controls which conversion tier is used."
  @type t :: :auto | :tier2

  @auto :auto
  @tier2 :tier2

  @doc "Automatically pick the best tier for the input (default)."
  @spec auto() :: t()
  def auto, do: @auto
  @doc "Always use the Tier-2 (`tl::parse` + walk) path, skipping Tier-1."
  @spec tier2() :: t()
  def tier2, do: @tier2

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:auto), do: "auto"
  def wire_value(:tier2), do: "tier2"
end
