# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f33f4b54c5a830d96176669bf47a7d15a67f5c03c508f53c87b0e09cfee8ae88
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.UriKind do
  @moduledoc "Semantic classification of an extracted URI."

  @typedoc "Semantic classification of an extracted URI."
  @type t :: :hyperlink | :image | :anchor | :citation | :reference | :email

  @hyperlink :hyperlink
  @image :image
  @anchor :anchor
  @citation :citation
  @reference :reference
  @email :email

  @doc "A clickable hyperlink (web URL, file link)."
  @spec hyperlink() :: t()
  def hyperlink, do: @hyperlink
  @doc "An image or media resource reference."
  @spec image() :: t()
  def image, do: @image
  @doc "An internal anchor or cross-reference target."
  @spec anchor() :: t()
  def anchor, do: @anchor
  @doc "A citation or bibliographic reference (DOI, academic ref)."
  @spec citation() :: t()
  def citation, do: @citation
  @doc "A general reference (e.g. `\\ref{}` in LaTeX, `:ref:` in RST)."
  @spec reference() :: t()
  def reference, do: @reference
  @doc "An email address (`mailto:` link or bare email)."
  @spec email() :: t()
  def email, do: @email

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:hyperlink), do: "hyperlink"
  def wire_value(:image), do: "image"
  def wire_value(:anchor), do: "anchor"
  def wire_value(:citation), do: "citation"
  def wire_value(:reference), do: "reference"
  def wire_value(:email), do: "email"
end
