# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:06e3857d9860692bf0cfb579f7d7fd89fce425e6c515b7588228c4c457897801
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.UserChunkConfig do
  @moduledoc "User-provided chunk configuration."

  @typedoc "User-provided chunk configuration."
  @type t :: %__MODULE__{
          page_ranges: [Xberg.PageRange.t()] | nil,
          pages_per_chunk: non_neg_integer() | nil,
          force_chunking: boolean(),
          disable_chunking: boolean()
        }

  defstruct page_ranges: nil,
            pages_per_chunk: nil,
            force_chunking: false,
            disable_chunking: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
