// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:54663ac7b8d0f031001e2b8315afeceb2e7ca1fe6d5eff04693634e2281e3394
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The meta-schema itself failed to compile.
/// </summary>
public class BadMetaSchemaException : LoadErrorException {
  public BadMetaSchemaException(string message) : base(message) {}

  public BadMetaSchemaException(string message, Exception innerException)
      : base(message, innerException) {}
}
