// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d504df0da52744bc43291b20e9193d08c2b3d6b295da4fc72628b11e9d9bf861
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// Browser backend used for JavaScript rendering.
/// </summary>
[JsonConverter(typeof(BrowserBackendJsonConverter))]
public enum BrowserBackend {
  /// <summary>
  /// Existing Chromium/CDP backend powered by chromiumoxide.
  /// </summary>
  [JsonPropertyName("chromiumoxide")] Chromiumoxide,
  /// <summary>
  /// Crawlberg-owned native browser backend derived from Obscura.
  /// </summary>
  [JsonPropertyName("native")] Native,
}

/// <summary>
/// Custom JSON converter for <see cref="BrowserBackend"/> that respects
/// explicit variant names.
/// </summary>
internal sealed class BrowserBackendJsonConverter
    : JsonConverter<BrowserBackend> {
  public override BrowserBackend Read(ref Utf8JsonReader reader,
                                      Type typeToConvert,
                                      JsonSerializerOptions options) {
    var value = reader.GetString();
    return value switch { "chromiumoxide" => BrowserBackend.Chromiumoxide,
                          "native" => BrowserBackend.Native,
                          _ => throw new JsonException(
                              $"Unknown BrowserBackend value: {value}") };
  }

  public override void Write(Utf8JsonWriter writer, BrowserBackend value,
                             JsonSerializerOptions options) {
    var str = value switch { BrowserBackend.Chromiumoxide => "chromiumoxide",
                             BrowserBackend.Native => "native",
                             _ => throw new JsonException(
                                 $"Unknown BrowserBackend value: {value}") };
    writer.WriteStringValue(str);
  }
}
