// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f6edfe3c31129d0ec38281be6cf603436b0a4d5094a2616af19657d4db55426f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Invalid configuration value.
/// </summary>
public class ConfigErrorException : HeuristicsErrorException {
  public ConfigErrorException(string message) : base(message) {}

  public ConfigErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
