// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8b3f59e589e3babf54aabea08d002c5ed774f05ac886ff22e3cdb8f1fde710dc
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file validates but cannot be deserialized into `Preset`.
/// </summary>
public class DeserializeException : LoadErrorException {
  public DeserializeException(string message) : base(message) {}

  public DeserializeException(string message, Exception innerException)
      : base(message, innerException) {}
}
