// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4a0e7e93f2db5ce4427e3183a42ac3ee8d91a4e01a8ae66ddf393323b7beb401
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The embedding model or embedding pipeline returned an error.
/// </summary>
public class EmbeddingException : XbergErrorException {
  public EmbeddingException(string message) : base(message) {}

  public EmbeddingException(string message, Exception innerException)
      : base(message, innerException) {}
}
