// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a8c9f0f2049383a36bd5809d7cb5bc7fd9ec57f7c932c18ec3e3963c1a73266b
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Non-fatal per-input extraction error captured by `ExtractionResult`.
/// </summary>
public sealed record ExtractionErrorItem {
  /// <summary>
  /// Input index in the original request.
  /// </summary>
  [JsonPropertyName("index")]
  public ulong Index { get; init; } = 0;

  /// <summary>
  /// Stable numeric error code.
  /// </summary>
  [JsonPropertyName("code")]
  public uint Code {
    get; init;
  } = 0;

  /// <summary>
  /// Stable snake_case error kind.
  /// </summary>
  [JsonPropertyName("error_type")]
  public required string ErrorType {
    get; init;
  }

  /// <summary>
  /// Best-effort source identifier.
  /// </summary>
  [JsonPropertyName("source")]
  public required string Source {
    get; init;
  }

  /// <summary>
  /// Error message.
  /// </summary>
  [JsonPropertyName("message")]
  public required string Message {
    get; init;
  }

  /// <summary>
  /// Parse a <see cref="ExtractionErrorItem"/> from a JSON string.
  /// </summary>
  /// <exception cref="XbergException">When the JSON cannot be
  /// deserialised.</exception>
  public static ExtractionErrorItem FromJson(string json) {
    try {
      return JsonSerializer.Deserialize<ExtractionErrorItem>(json,
                                                             JsonOptions) ??
             throw new XbergException(
                 $"Failed to parse ExtractionErrorItem from JSON: deserializer returned null");
    } catch (XbergException) {
      throw;
    } catch (Exception e) {
      throw new XbergException(
          $"Failed to parse ExtractionErrorItem from JSON: {e.Message}", e);
    }
  }

  private static readonly JsonSerializerOptions JsonOptions = new() {
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
    Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower),
                   new ByteArrayJsonConverter() },
  };

  /// <summary>Options for serializing config/input objects to FFI. Strips nulls
  /// (nullable C# fields default to null and would override required Rust
  /// fields with non-deserialisable nulls) but preserves explicit false/0 so
  /// caller intent is kept.</summary>
  private static readonly JsonSerializerOptions JsonSerializationOptions =
      new() {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(
                           JsonNamingPolicy.SnakeCaseLower),
                       new ByteArrayJsonConverter() },
      };
}
