// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:87b8a165b5c64d4b9bea1bd8e0d63b0144d1ce8df75dc7b7fbf4b4c9e045a941
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors that can occur during heuristics analysis.
/// </summary>
public class HeuristicsErrorException : XbergException {
  public HeuristicsErrorException(string message) : base(message) {}

  public HeuristicsErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
