// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4eb202e482c066004357cb4fd655ec8cebf8b911e6153b9decaf0b79aa56fb21
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An image manipulation operation (resize, decode, DPI conversion) failed.
/// </summary>
public class ImageProcessingException : XbergErrorException {
  public ImageProcessingException(string message) : base(message) {}

  public ImageProcessingException(string message, Exception innerException)
      : base(message, innerException) {}
}
