// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:551916e6b0763c74b056de1b7f9e7f7fcfd24681ef9ea67b1e885dd009af1486
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A filesystem I/O error occurred while reading a preset directory.
/// </summary>
public class IoException : LoadErrorException {
  public IoException(string message) : base(message) {}

  public IoException(string message, Exception innerException)
      : base(message, innerException) {}
}
