// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:611a61a941245697888c32a1c79d85626e39fa4fe5f7c05341c2c94157a14ec4
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An internal `Mutex` or `RwLock` was found in a poisoned state.
/// </summary>
public class LockPoisonedException : XbergErrorException {
  public LockPoisonedException(string message) : base(message) {}

  public LockPoisonedException(string message, Exception innerException)
      : base(message, innerException) {}
}
