// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3b4f3f15d62b1cc30530d4bf11f1595fc3af573d7a49122f05c74a0b953a3c6d
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file is not valid JSON.
/// </summary>
public class ParseException : LoadErrorException {
  public ParseException(string message) : base(message) {}

  public ParseException(string message, Exception innerException)
      : base(message, innerException) {}
}
