// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:faa55a359568d8cde3225df544e32387024cac34ce30b99e3b1c709fc97bf625
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// PDF analysis step failed (only when `heuristics-pdf` feature is active).
/// </summary>
public class PdfAnalysisErrorException : HeuristicsErrorException {
  public PdfAnalysisErrorException(string message) : base(message) {}

  public PdfAnalysisErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
