// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9fe4502bca77c4312e04c571b3397dba73824492aa7fa315f319e51399c36f47
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The reranker model or reranking pipeline returned an error.
/// </summary>
public class RerankingException : XbergErrorException {
  public RerankingException(string message) : base(message) {}

  public RerankingException(string message, Exception innerException)
      : base(message, innerException) {}
}
