// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f904b0df94dc89396f13a375c07e698bce145e703690885b1af31c777b0fde57
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while resolving a preset against caller overrides.
/// </summary>
public class ResolveErrorException : XbergException {
  public ResolveErrorException(string message) : base(message) {}

  public ResolveErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
