// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:dffb965bad643b7fec78fa7e9ff7782501a13224afb2a729ea2ab1e0b4d1e8dc
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file parses as JSON but does not validate against the meta-schema.
/// </summary>
public class SchemaValidationException : LoadErrorException {
  public SchemaValidationException(string message) : base(message) {}

  public SchemaValidationException(string message, Exception innerException)
      : base(message, innerException) {}
}
