// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d2772d70adec38884d22093440f19a1f07aaaaa233eab9568c956ef9f29f9719
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// JSON or MessagePack serialization/deserialization failed.
/// </summary>
public class SerializationException : XbergErrorException {
  public SerializationException(string message) : base(message) {}

  public SerializationException(string message, Exception innerException)
      : base(message, innerException) {}
}
