// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8f071dbe55eebef432d4fa4acd1b7d0cd57f798fa670cfd03d03964996990260
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The extraction operation exceeded the configured time limit.
/// </summary>
public class TimeoutException : XbergErrorException {
  public TimeoutException(string message) : base(message) {}

  public TimeoutException(string message, Exception innerException)
      : base(message, innerException) {}
}
