// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4d9babdd2476102d48c99203953d9b7c4a645ee80ce79e1bd8c033ad18a752c9
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Audio/video transcription failed.
/// </summary>
public class TranscriptionException : XbergErrorException {
  public TranscriptionException(string message) : base(message) {}

  public TranscriptionException(string message, Exception innerException)
      : base(message, innerException) {}
}
