// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:462771ba824d6ca334a51662e4b9d52a11b96673f1d735ced0bc3d3164c9ea0d
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The document's MIME type is not supported by any registered extractor.
/// </summary>
public class UnsupportedFormatException : XbergErrorException {
  public UnsupportedFormatException(string message) : base(message) {}

  public UnsupportedFormatException(string message, Exception innerException)
      : base(message, innerException) {}
}
