// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:eb20c8e46b7e2723a44c12033c1f92006ffbe16cbc6987c1faad976ec7b4708d
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { extract, extractBatch, ExtractInput, type ExtractionConfig, ExtractInputKind } from "@xberg-io/xberg";

process.env.CRAWLBERG_ALLOW_PRIVATE_NETWORK ??= "true";
process.env.RUST_MIN_STACK ??= "16777216";


async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let buffer = await response.arrayBuffer();

	if (contentEncoding === "gzip") {
		const { gunzipSync } = await import("zlib");
		buffer = gunzipSync(new Uint8Array(buffer)).buffer;
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		buffer = brotliDecompressSync(new Uint8Array(buffer)).buffer;
	}

	const text = new TextDecoder().decode(buffer);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("batch", () => {

	it("extract_batch_bytes_happy: extract_batch: happy path with mixed inputs", async () => {
		const result = await extractBatch([{ bytes: Uint8Array.from([72, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 33]), kind: ExtractInputKind.Bytes, mimeType: "text/plain" } as ExtractInput, { bytes: Uint8Array.from([60, 104, 116, 109, 108, 62, 60, 98, 111, 100, 121, 62, 84, 101, 115, 116, 60, 47, 98, 111, 100, 121, 62, 60, 47, 104, 116, 109, 108, 62]), kind: ExtractInputKind.Bytes, mimeType: "text/html" } as ExtractInput]);
    expect(result.results.length).toBeGreaterThanOrEqual(1);

	}, 30000);

	it("extract_batch_bytes_invalid_mime: extract_batch with invalid bytes MIME type", async () => {
		const result = await extractBatch([{ bytes: Uint8Array.from([72, 101, 108, 108, 111]), kind: ExtractInputKind.Bytes, mimeType: "application/x-nonexistent" } as ExtractInput]);
    expect(result).toBeDefined();

	}, 30000);

	it("extract_batch_bytes_mixed_format: extract_batch: handles unsupported MIME gracefully", async () => {
		const result = await extractBatch([{ bytes: Uint8Array.from([80, 68, 70, 32, 112, 108, 97, 99, 101, 104, 111, 108, 100, 101, 114]), kind: ExtractInputKind.Bytes, mimeType: "application/x-unknown" } as ExtractInput]);
    expect(result).toBeDefined();

	}, 30000);

	it("extract_batch_bytes_unsupported_mime: extract_batch with unsupported bytes MIME type", async () => {
		const result = await extractBatch([{ bytes: Uint8Array.from([100, 97, 116, 97]), kind: ExtractInputKind.Bytes, mimeType: "application/x-unknown" } as ExtractInput]);
    expect(result).toBeDefined();

	}, 30000);

	it("extract_batch_empty_inputs: extract_batch: empty batch", async () => {
		const result = await extractBatch([]);
    expect(result.results.length).toBe(0);

	}, 30000);

	it("extract_batch_uri_all_missing: extract_batch with missing URI inputs", async () => {
		const result = await extractBatch([{ kind: ExtractInputKind.Uri, uri: "/nonexistent/a.pdf" } as ExtractInput, { kind: ExtractInputKind.Uri, uri: "/nonexistent/b.txt" } as ExtractInput]);
    expect(result.summary?.results).toBe(0);
    expect(result.summary?.errors).toBe(2);

	}, 30000);

	it("extract_batch_uri_basic: extract_batch over URI inputs", async () => {
		const inputsMockBaseUrl = process.env.MOCK_SERVER_EXTRACT_BATCH_URI_BASIC ?? `${process.env.MOCK_SERVER_URL}/fixtures/extract_batch_uri_basic`;
		const result = await extractBatch([{ kind: ExtractInputKind.Uri, uri: `${inputsMockBaseUrl}/pdf/fake_memo.pdf` } as ExtractInput, { kind: ExtractInputKind.Uri, uri: `${inputsMockBaseUrl}/text/fake_text.txt` } as ExtractInput]);
    expect(result.results.length).toBeGreaterThanOrEqual(2);

	}, 30000);

	it("extract_batch_uri_not_found: extract_batch with missing URI input", async () => {
		const result = await extractBatch([{ kind: ExtractInputKind.Uri, uri: "/nonexistent/a.pdf" } as ExtractInput]);
    expect(result.summary?.results).toBe(0);
    expect(result.summary?.errors).toBe(1);

	}, 30000);

	it("extract_batch_uri_partial_failure: extract_batch with one valid URI input and one that downloads to an unparseable document", async () => {
		const inputsMockBaseUrl = process.env.MOCK_SERVER_EXTRACT_BATCH_URI_PARTIAL_FAILURE ?? `${process.env.MOCK_SERVER_URL}/fixtures/extract_batch_uri_partial_failure`;
		const result = await extractBatch([{ kind: ExtractInputKind.Uri, uri: `${inputsMockBaseUrl}/text/plain.txt` } as ExtractInput, { kind: ExtractInputKind.Uri, uri: `${inputsMockBaseUrl}/pdf/corrupt_truncated.pdf` } as ExtractInput]);
    expect(result.summary?.results).toBe(1);
    expect(result.summary?.errors).toBe(1);

	}, 30000);

});
