// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:abac2b4f7fd4ebceac3f58301c7d00432b14dd8dbde811980d8d787ccd2cc3f4
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { extract, ExtractInput, type ExtractionConfig, ExtractInputKind } from "@xberg-io/xberg";

process.env.CRAWLBERG_ALLOW_PRIVATE_NETWORK ??= "true";
process.env.RUST_MIN_STACK ??= "16777216";


async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let buffer = await response.arrayBuffer();

	if (contentEncoding === "gzip") {
		const { gunzipSync } = await import("zlib");
		buffer = gunzipSync(new Uint8Array(buffer)).buffer;
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		buffer = brotliDecompressSync(new Uint8Array(buffer)).buffer;
	}

	const text = new TextDecoder().decode(buffer);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("format_specific", () => {

	it("format_docx_equations: DOCX equations extract to LaTeX math in markdown output", async () => {
		const inputMockBaseUrl = process.env.MOCK_SERVER_FORMAT_DOCX_EQUATIONS ?? `${process.env.MOCK_SERVER_URL}/fixtures/format_docx_equations`;
		const result = await extract({ filename: "equations.docx", kind: ExtractInputKind.Uri, mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", uri: `${inputMockBaseUrl}/docx/equations.docx` } as ExtractInput, { outputFormat: "markdown" } as ExtractionConfig);
    expect(result.results?.[0]?.content.length).toBeGreaterThanOrEqual(20);
    expect(result.results?.[0]?.content ?? "").toContain("$");

	}, 30000);

	it("format_docx_standalone: Standalone DOCX extraction using extract", async () => {
		const inputMockBaseUrl = process.env.MOCK_SERVER_FORMAT_DOCX_STANDALONE ?? `${process.env.MOCK_SERVER_URL}/fixtures/format_docx_standalone`;
		const result = await extract({ filename: "fake.docx", kind: ExtractInputKind.Uri, mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", uri: `${inputMockBaseUrl}/docx/fake.docx` } as ExtractInput);
    expect(result.results?.[0]?.content.length).toBeGreaterThanOrEqual(20);

	}, 30000);

	it("format_hwpx_standalone: Standalone HWPX extraction using extract", async () => {
		const inputMockBaseUrl = process.env.MOCK_SERVER_FORMAT_HWPX_STANDALONE ?? `${process.env.MOCK_SERVER_URL}/fixtures/format_hwpx_standalone`;
		const result = await extract({ filename: "simple.hwpx", kind: ExtractInputKind.Uri, mimeType: "application/haansofthwpx", uri: `${inputMockBaseUrl}/hwpx/simple.hwpx` } as ExtractInput);
    expect(result.results?.[0]?.content.length).toBeGreaterThanOrEqual(20);
    expect(result.results?.[0]?.content ?? "").toContain("Hello from HWPX");

	}, 30000);

	it("format_pdf_text: Standalone PDF text extraction using extract", async () => {
		const inputMockBaseUrl = process.env.MOCK_SERVER_FORMAT_PDF_TEXT ?? `${process.env.MOCK_SERVER_URL}/fixtures/format_pdf_text`;
		const result = await extract({ filename: "fake_memo.pdf", kind: ExtractInputKind.Uri, mimeType: "application/pdf", uri: `${inputMockBaseUrl}/pdf/fake_memo.pdf` } as ExtractInput);
    expect(result.results?.[0]?.content.length).toBeGreaterThanOrEqual(50);
    expect(["Mallori", "May"].some((v) => result.results?.[0]?.content.includes(v))).toBe(true);

	}, 30000);

	it("format_pptx: PPTX presentation extraction using extract", async () => {
		const inputMockBaseUrl = process.env.MOCK_SERVER_FORMAT_PPTX ?? `${process.env.MOCK_SERVER_URL}/fixtures/format_pptx`;
		const result = await extract({ kind: ExtractInputKind.Uri, mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation", uri: `${inputMockBaseUrl}/pptx/simple.pptx` } as ExtractInput);
    expect(result).toBeDefined();

	}, 30000);

	it("format_xlsx: XLSX spreadsheet extraction using extract", async () => {
		const inputMockBaseUrl = process.env.MOCK_SERVER_FORMAT_XLSX ?? `${process.env.MOCK_SERVER_URL}/fixtures/format_xlsx`;
		const result = await extract({ kind: ExtractInputKind.Uri, mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", uri: `${inputMockBaseUrl}/xlsx/stanley_cups.xlsx` } as ExtractInput);
    expect(result).toBeDefined();

	}, 30000);

});
