// Generated by alef. Do not edit by hand.
// alef:hash:e3a3f0d7a228b1ca744cd9602bf1c3f5b20755960a0af6edc2e873cee3eb9a56
// swift-format-ignore-file
// This file contains generated FFI glue for plugin Box classes.

import Foundation

/// Opaque box class retained by Rust via `Unmanaged<SwiftTokenizerBackendBox>.passRetained`.
/// Wraps `any SwiftTokenizerBackendBridge` and exposes `alef_*` FFI shim methods.
/// swift-bridge @_cdecl shims call these methods directly.
public final class SwiftTokenizerBackendBox {
    private let bridge: any SwiftTokenizerBackendBridge
    public init(_ bridge: any SwiftTokenizerBackendBridge) { self.bridge = bridge }
    // MARK: Plugin super-trait shims

    public func alef_name() -> RustString {
        return RustString(bridge.name)
    }

    public func alef_version() -> RustString {
        return RustString(bridge.version())
    }

    public func alef_initialize() -> String {
        do {
            try bridge.initialize()
            return encodeOkVoidEnvelope()
        } catch { return encodeErrEnvelope("\(error)") }
    }

    public func alef_shutdown() -> String {
        do {
            try bridge.shutdown()
            return encodeOkVoidEnvelope()
        } catch { return encodeErrEnvelope("\(error)") }
    }

    // MARK: Trait-specific shims
    public func alef_count_tokens(text: RustString) -> UInt {
        return UInt(bridge.countTokens(text: text.toString()))
    }
}
