# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d573c1bdd0b223d3ec29312f13e52065a5efc0e4bf1f5adb8cca8efca095a8b8
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: summarization."""

import json
import os

import pytest
from xberg import ExtractInput, ExtractInputKind, ExtractionConfig, SummarizationConfig, SummaryStrategy, extract


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


@pytest.mark.asyncio
async def test_summarization_extractive_smoke() -> None:
    """TextRank extractive summary over a multi-paragraph plain text document. Pure-Rust, deterministic, no external services required."""
    input_mock_base_url = os.environ["MOCK_SERVER_URL"] + "/fixtures/summarization_extractive_smoke"
    input_json = '{"kind":"uri","uri":"$mock_url/text/book_war_and_peace_1p.txt"}'.replace(
        "$mock_url", input_mock_base_url
    )
    input_data = json.loads(input_json)
    input = ExtractInput(kind=ExtractInputKind("uri"), uri=input_data["uri"])
    config = ExtractionConfig(summarization=SummarizationConfig(max_tokens=80, strategy=SummaryStrategy("extractive")))

    result = await extract(input, config)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "text/plain".lower()
    assert (result.results[0].summary.text if result.results[0].summary else None) is not None and (
        not hasattr(result.results[0].summary.text if result.results[0].summary else None, "__len__")
        or len(result.results[0].summary.text if result.results[0].summary else None) > 0
    )
    assert (
        _alef_e2e_text(result.results[0].summary.strategy if result.results[0].summary else None).lower()
        == "extractive".lower()
    )
