# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:18001c3f9a119b9dc78931cd96d49921c7688d8d81c91bbfb79e6f71f3989971
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: url."""

import json
import os

import pytest
from xberg import (
    CrawlConfig,
    ExtractInput,
    ExtractInputKind,
    ExtractionConfig,
    UrlExtractionConfig,
    UrlExtractionMode,
    extract,
    extract_batch,
)


@pytest.mark.asyncio
async def test_url_batch_mixed_inputs() -> None:
    """extract_batch: mixed bytes and URL inputs share one output envelope."""
    inputs_mock_base_url = os.environ["MOCK_SERVER_URL"] + "/fixtures/url_batch_mixed_inputs"
    inputs_json = '[{"kind":"uri","uri":"$mock_url"},{"bytes":[66,97,116,99,104,32,98,121,116,101,115,32,99,111,110,116,101,110,116],"filename":"inline.txt","kind":"bytes","mime_type":"text/plain"}]'.replace(
        "$mock_url", inputs_mock_base_url
    )
    inputs_data = json.loads(inputs_json)
    inputs = [
        ExtractInput(kind=ExtractInputKind("uri"), uri=inputs_data[0]["uri"]),
        ExtractInput(
            bytes=inputs_data[1]["bytes"],
            filename=inputs_data[1]["filename"],
            kind=ExtractInputKind("bytes"),
            mime_type=inputs_data[1]["mime_type"],
        ),
    ]
    config = ExtractionConfig(url=UrlExtractionConfig(mode=UrlExtractionMode("document")))

    result = await extract_batch(inputs, config)
    assert len(result.results) >= 2
    assert "Batch URL document content".lower() in str(result.results[0].content).lower()
    assert "Batch bytes content" in result.results[1].content


@pytest.mark.asyncio
async def test_url_crawl_linked_pages() -> None:
    """extract: crawl mode follows linked pages."""
    input_mock_base_url = (
        os.environ.get("MOCK_SERVER_URL_CRAWL_LINKED_PAGES")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/url_crawl_linked_pages"
    )
    input_json = '{"kind":"uri","uri":"$mock_url"}'.replace("$mock_url", input_mock_base_url)
    input_data = json.loads(input_json)
    input = ExtractInput(kind=ExtractInputKind("uri"), uri=input_data["uri"])
    config = ExtractionConfig(
        url=UrlExtractionConfig(
            crawl=CrawlConfig(max_depth=1, max_pages=4, respect_robots_txt=False), mode=UrlExtractionMode("crawl")
        )
    )

    result = await extract(input, config)
    assert result.summary.pages_crawled >= 2
    assert "About crawl target" in result.results[1].content


@pytest.mark.asyncio
async def test_url_html_page_extract() -> None:
    """extract: website URL returns page content."""
    input_mock_base_url = os.environ["MOCK_SERVER_URL"] + "/fixtures/url_html_page_extract"
    input_json = '{"kind":"uri","uri":"$mock_url"}'.replace("$mock_url", input_mock_base_url)
    input_data = json.loads(input_json)
    input = ExtractInput(kind=ExtractInputKind("uri"), uri=input_data["uri"])
    config = ExtractionConfig(url=UrlExtractionConfig(mode=UrlExtractionMode("document")))

    result = await extract(input, config)
    assert "Xberg URL Page".lower() in str(result.results[0].content).lower()
    assert len(result.results) >= 1


@pytest.mark.asyncio
async def test_url_recursive_document_urls() -> None:
    """extract: recursive URL extraction follows document links discovered in results."""
    input_mock_base_url = (
        os.environ.get("MOCK_SERVER_URL_RECURSIVE_DOCUMENT_URLS")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/url_recursive_document_urls"
    )
    input_json = '{"kind":"uri","uri":"$mock_url"}'.replace("$mock_url", input_mock_base_url)
    input_data = json.loads(input_json)
    input = ExtractInput(kind=ExtractInputKind("uri"), uri=input_data["uri"])
    config = ExtractionConfig(
        url=UrlExtractionConfig(
            crawl=CrawlConfig(document_url_depth=1, follow_document_urls=True, respect_robots_txt=False),
            mode=UrlExtractionMode("document"),
        )
    )

    result = await extract(input, config)
    assert len(result.results) >= 2
    assert "Recursive document target" in result.results[1].content


@pytest.mark.asyncio
async def test_url_remote_text_document() -> None:
    """extract: remote text document URL."""
    input_mock_base_url = os.environ["MOCK_SERVER_URL"] + "/fixtures/url_remote_text_document"
    input_json = '{"kind":"uri","uri":"$mock_url"}'.replace("$mock_url", input_mock_base_url)
    input_data = json.loads(input_json)
    input = ExtractInput(kind=ExtractInputKind("uri"), uri=input_data["uri"])
    config = ExtractionConfig(url=UrlExtractionConfig(mode=UrlExtractionMode("document")))

    result = await extract(input, config)
    assert "Remote document hello".lower() in str(result.results[0].content).lower()
    assert result.summary.remote_urls == 1
