# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e92dc9cfcad84c4a739407c1594f4e2cb8413a4413d9c88d75ad157b03520de3
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: validator_management."""

from xberg import clear_validators, list_validators


def test_validators_clear() -> None:
    """Clear all validators and verify list is empty."""
    clear_validators()


def test_validators_list() -> None:
    """List all registered validators."""
    result = list_validators()
    assert result is not None
