# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:81a0a395bf9323a0abbfc0d5016629800327f1452c4c4bbe799a275bf70052ff
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: ocr_backend_management."""

from xberg import clear_ocr_backends, list_ocr_backends, unregister_ocr_backend


def test_ocr_backends_clear() -> None:
    """Clear all OCR backends and verify list is empty."""
    clear_ocr_backends()


def test_ocr_backends_list() -> None:
    """List all registered OCR backends."""
    result = list_ocr_backends()
    assert result is not None


def test_ocr_backends_unregister() -> None:
    """Unregister nonexistent OCR backend gracefully."""
    name = "nonexistent-backend-xyz"

    unregister_ocr_backend(name)
