# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:247774c828e9dae272d6e9e21c1df5bdae815aac80080a0e0e1268b7793887f5
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: renderer_management."""

from xberg import clear_renderers, list_renderers


def test_renderers_clear() -> None:
    """Clear all renderers and verify list is empty."""
    clear_renderers()


def test_renderers_list() -> None:
    """List all registered renderers."""
    result = list_renderers()
    assert result is not None
