# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:13d811e7bf4642151c7b10a7f07bd4c37b63d4eebcaa3d66426f3f25b33ad361
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'reranker_backend_management' do

  it 'clear_reranker_backends: Clear all reranker backends and verify list is empty' do
    expect { Xberg.clear_reranker_backends() }.not_to raise_error

  end


  it 'list_reranker_backends: List all registered reranker backends' do
    result = Xberg.list_reranker_backends()

    expect(result).not_to be_nil
  end

end
