// Generated by alef. Do not edit by hand.
// alef:hash:4bd21e7da8a30d5bce36d39d38f4d0c43e318ed1e2fd204df2c74ff8a8ea4908

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "xberg-android"
