# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d60e6061fd27523b161ad5bd0f930b762938f95d81b83d600d5656c75ada8dcf
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: code
defmodule E2e.CodeTest do
  use ExUnit.Case, async: false

  describe "code_shebang_detection" do
    test "code_shebang_detection" do
      input_mock_base_url =
        System.get_env("MOCK_SERVER_CODE_SHEBANG_DETECTION") || "#{System.get_env("MOCK_SERVER_URL")}/fixtures/code_shebang_detection"

      input_value = %Xberg.ExtractInput{
        kind: "uri",
        mime_type: "text/x-source-code",
        uri: String.replace("$mock_url/code/script.sh", "$mock_url", input_mock_base_url)
      }

      {:ok, result} = Xberg.extract(input: input_value)
      assert Enum.at(result.results, 0).mime_type == "text/x-source-code"

      assert (is_binary(Enum.at(result.results, 0).content) && byte_size(Enum.at(result.results, 0).content) >= 10) ||
               (is_list(Enum.at(result.results, 0).content) && length(Enum.at(result.results, 0).content) >= 10)

      assert String.contains?(to_string(Enum.at(result.results, 0).content), "build")
      assert String.contains?(to_string(Enum.at(result.results, 0).content), "clean")
    end
  end
end
