// Generated by alef. Do not edit by hand.
// alef:hash:d6409ce1e4a05a62948e63525322f9cabbc9b1b249733fafa0ba2221df6f61a0
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Element attributes in Djot.
 *
 * Represents the attributes attached to elements using {.class #id key="value"} syntax.
 */
data class Attributes(
    /** Element ID (#identifier) */
    val id: String? = null,
    /** CSS classes (.class1 .class2) */
    val classes: List<String> = emptyList(),
    /** Key-value pairs (key="value") */
    val keyValues: List<KeyValueAttribute> = emptyList(),
)
