// Generated by alef. Do not edit by hand.
// alef:hash:47fc759885254eb70c28e4b46e774fb4ff3161f5dfa965eb2989c7eda4458241
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Configuration for GeoJSON extraction.
 *
 * GeoJSON coordinates can dominate extraction output and duplicate large geometry
 * payloads in rendered content and metadata. The default therefore emits a bounded
 * aggregate summary. Set `Self.include_full_coordinates` only when callers need
 * every coordinate in the extracted text and accept output proportional to the input.
 */
data class GeoJsonExtractionConfig(
    /**
     * Include every coordinate in rendered content and `flattened_fields` metadata.
     *
     * Defaults to `false`. When false, extraction reports feature, property, geometry,
     * position-count, bounds, truncation, and discarded-category metadata and emits a
     * `ProcessingWarning` for every GeoJSON input.
     */
    val includeFullCoordinates: Boolean = false,
)
