// Generated by alef. Do not edit by hand.
// alef:hash:619fec68ef0fd7ee5f9f54e69e3b25802cada1c2bb3d27ee1f8c129bcd189c2d

package io.xberg

object PostProcessorBridge {
    private val registered = mutableMapOf<String, IPostProcessor>()

    fun register(impl: IPostProcessor): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterPostProcessor(PostProcessorJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterPostProcessor(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearPostProcessors()
    }

    fun getAll(): Map<String, IPostProcessor> = registered.toMap()
}
