// Generated by alef. Do not edit by hand.
// alef:hash:29608304bf9240513092afa459c9f76c73033627961b1f9f11d4b77b8c109dc8
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** RAKE-specific parameters. */
data class RakeParams(
    /** Minimum word length to consider (default: 1). */
    val minWordLength: Long = 1L,
    /** Maximum words in a keyword phrase (default: 3). */
    val maxWordsPerPhrase: Long = 3L,
)
