// Generated by alef. Do not edit by hand.
// alef:hash:9b155c226eb0646348aee12513823d144948674a89bcadee88fc650d130f45b3

package io.xberg

object RerankerBackendBridge {
    private val registered = mutableMapOf<String, IRerankerBackend>()

    fun register(impl: IRerankerBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterRerankerBackend(RerankerBackendJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterRerankerBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearRerankerBackends()
    }

    fun getAll(): Map<String, IRerankerBackend> = registered.toMap()
}
