// Generated by alef. Do not edit by hand.
// alef:hash:bd83e2eb26d3662fafb1ff33da206f35a8646d2d0b937968b43bd3ab083a6637
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Configuration for the summarisation post-processor. */
data class SummarizationConfig(
    /** Summarisation strategy. */
    val strategy: SummaryStrategy = SummaryStrategy.EXTRACTIVE,
    /** Maximum summary length in tokens. `null` lets the backend pick a default. */
    val maxTokens: Int? = null,
    /**
     * LLM configuration for the abstractive backend. Ignored when
     * `strategy = Extractive`. Required when `strategy = Abstractive`.
     */
    val llm: LlmConfig? = null,
)
