// Generated by alef. Do not edit by hand.
// alef:hash:2b9f6658b6c547083520c73e211178cd0d587b3c5f64ffc354ada8bcd89728d4
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Controls which conversion tier is used. */
enum class TierStrategy {
    /**
     * Automatically pick the best tier for the input (default).
     *
     * Runs the classifier against the prescan report and uses Tier-1 when
     * eligible; falls back to Tier-2 on bail or when the classifier routes
     * to Tier-2.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("auto") AUTO,
    /** Always use the Tier-2 (`tl.parse` + walk) path, skipping Tier-1. */
    @com.fasterxml.jackson.annotation.JsonProperty("tier2") TIER2;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            AUTO -> "auto"
            TIER2 -> "tier2"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): TierStrategy =
            when (value) {
                "auto" -> AUTO
                "tier2" -> TIER2
                else -> throw IllegalArgumentException("Unknown TierStrategy value: $value")
            }
    }
}
