// Generated by alef. Do not edit by hand.
// alef:hash:d16e6eb412767ece5b7cbadfc05a55beba138d04fc71c3ae1277e029686a2a18

package io.xberg

object TokenizerBackendBridge {
    private val registered = mutableMapOf<String, ITokenizerBackend>()

    fun register(impl: ITokenizerBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterTokenizerBackend(TokenizerBackendJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterTokenizerBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearTokenizerBackends()
    }

    fun getAll(): Map<String, ITokenizerBackend> = registered.toMap()
}
