// Generated by alef. Do not edit by hand.
// alef:hash:e421751ddb1bdb5b49abe614910e474126d50df018dd0ddba060ff2f1ff1ee8f
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** FictionBook (FB2) metadata. */
data class FictionBookMetadata(
    /** Genre tags as declared in the FB2 `<genre>` elements. */
    val genres: List<String> = emptyList(),
    /** Book series (sequence) names, if any. */
    val sequences: List<String> = emptyList(),
    /** Short annotation / summary from the FB2 `<annotation>` element. */
    val annotation: String? = null,
)
