// Generated by alef. Do not edit by hand.
// alef:hash:4cff0c246e854938dc4646255c75dd25e18fb0ca1dd17f452147cf013bb49ec1
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Image preprocessing configuration for OCR.
 *
 * These settings control how images are preprocessed before OCR to improve
 * text recognition quality. Different preprocessing strategies work better
 * for different document types.
 */
data class ImagePreprocessingConfig(
    /** Target DPI for the image (300 is standard, 600 for small text). */
    val targetDpi: Int = 300,
    /** Auto-detect and correct image rotation. */
    val autoRotate: Boolean = false,
    /** Correct skew (tilted images). Must be `false` with `none` or `off` binarization. */
    val deskew: Boolean = true,
    /** Remove noise from the image. */
    val denoise: Boolean = false,
    /**
     * Enhance contrast for better text visibility. With `none` or `off` binarization, this
     * applies background normalization and sharpening while preserving grayscale pixels.
     */
    val contrastEnhance: Boolean = false,
    /**
     * Binarization method: "none" (alias "off"), "otsu", "sauvola", or "adaptive".
     * `deskew` must be `false` when this is `none` or `off`.
     */
    val binarizationMethod: String = "otsu",
    /** Invert colors (white text on black → black on white). */
    val invertColors: Boolean = false,
)
