// Generated by alef. Do not edit by hand.
// alef:hash:b4ceede4da26e171c93cf36f88c9564fa6ef22142c403838da6be9b36d03f980
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Language detection configuration. */
data class LanguageDetectionConfig(
    /** Enable language detection */
    val enabled: Boolean = true,
    /** Minimum confidence threshold (0.0-1.0) */
    val minConfidence: Double = 0.8,
    /** Detect multiple languages in the document */
    val detectMultiple: Boolean = false,
)
