// Generated by alef. Do not edit by hand.
// alef:hash:2ba708373eb8b34763c42c2b6d83c6c327e786046c980631ef6f8f6566f7defb
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Selects which evidence is authoritative when Xberg infers a MIME type. */
enum class MimeDetectionPolicy {
    /** Prefer a supported content signature, falling back to the filename extension. */
    @com.fasterxml.jackson.annotation.JsonProperty("prefer_content") PREFER_CONTENT,
    /**
     * Trust a supported filename extension without reading content for detection.
     *
     * # Security
     *
     * Filenames are attacker-controlled input in uploads and downloads. Use this only for trusted sources;
     * otherwise a misleading extension can route arbitrary content to the wrong extractor.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("trust_extension") TRUST_EXTENSION,
    /** Ignore the filename extension and require content-based detection. */
    @com.fasterxml.jackson.annotation.JsonProperty("content_only") CONTENT_ONLY;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            PREFER_CONTENT -> "prefer_content"
            TRUST_EXTENSION -> "trust_extension"
            CONTENT_ONLY -> "content_only"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): MimeDetectionPolicy =
            when (value) {
                "prefer_content" -> PREFER_CONTENT
                "trust_extension" -> TRUST_EXTENSION
                "content_only" -> CONTENT_ONLY
                else -> throw IllegalArgumentException("Unknown MimeDetectionPolicy value: $value")
            }
    }
}
