// Generated by alef. Do not edit by hand.
// alef:hash:b77580a074c10c5325948530900b0f28ba7f5a723e16f3cce8c8de64b96a5098
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Translation of the extracted content.
 *
 * Holds the translated rendition of `ExtractedDocument.content` and (when
 * `preserve_markup` was requested) the translated `formatted_content`. Chunks
 * are translated in place inside `ExtractedDocument.chunks[*].content` rather
 * than duplicated here.
 */
data class Translation(
    /** BCP-47 language tag the translation was produced into (e.g. `"de"`, `"fr-CA"`). */
    val targetLang: String,
    /** BCP-47 source language. `null` when the translation backend was asked to detect. */
    val sourceLang: String? = null,
    /** Translated plain-text body. Matches the shape of `ExtractedDocument.content`. */
    val content: String,
    /**
     * Translated markup body (Markdown / HTML / etc.) when `preserve_markup` was
     * enabled on the config. `null` otherwise.
     */
    val formattedContent: String? = null,
)
