// Generated by alef. Do not edit by hand.
// alef:hash:5598bdf5ea5824e32a89d75a331699745243dbfa16788bc6cbc25f1d7e520443

package io.xberg

class XbergBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
