// DO NOT EDIT - auto-generated by alef
// alef:hash:1c2393a3536412c655c630a084d9377d8af37dc997638ed07c88ea6ff1db2814
package io.xberg;

/**
 * A cache read or write operation failed.
 */
public class CacheException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CacheException with the given message. */
  public CacheException(final String message) {
    super(message);
  }

  /** Creates a new CacheException with the given message and cause. */
  public CacheException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
