// DO NOT EDIT - auto-generated by alef
// alef:hash:5531113284449faf3ed55a70fe0b1ffad903f35fee9c733cb28f5fd97487332b
package io.xberg;

/**
 * The extraction stopped after a cooperative cancellation request.
 *
 * Rust callers can request cancellation through
 * `CancellationToken`. The REST async-jobs API uses the
 * same mechanism. Generated language bindings do not currently expose
 * in-process cancellation.
 */
public class CancelledException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CancelledException with the given message. */
  public CancelledException(final String message) {
    super(message);
  }

  /** Creates a new CancelledException with the given message and cause. */
  public CancelledException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
