// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:855ecb92675166767c6a55f0ea7a412e5e5c2c7cee7e5f0bc822b107b77f062e
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Code block fence style in Markdown output.
 *
 * Determines how code blocks ({@code &lt;pre&gt;&lt;code&gt;}) are rendered in Markdown.
 */
@SuppressWarnings("PMD")
public enum CodeBlockStyle {
    /**
     * Indented code blocks (4 spaces). {@code CommonMark} standard.
     */
    Indented("Indented"),
    /**
     * Fenced code blocks with triple backticks. Default (GFM). Supports language hints.
     */
    Backticks("Backticks"),
    /**
     * Fenced code blocks with tildes (~~~). Supports language hints.
     */
    Tildes("Tildes");


    /** The string value. */
    private final String value;

    CodeBlockStyle(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static CodeBlockStyle fromValue(final String value) {
        for (CodeBlockStyle e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown CodeBlockStyle value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
