// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1aab45ce3361c24f167e63dc578b4de5019774eee34c6983b99e3d8b083355e1
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

/** Exception thrown when the Rust core reports an unknown error. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class CoreErrorException extends XbergRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CoreErrorException. */
  public CoreErrorException(final String message) {
    super(2, message);
  }

  /** Creates a new CoreErrorException with a cause. */
  public CoreErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
