// DO NOT EDIT - auto-generated by alef
// alef:hash:47e88cc60c44cd0183b55e9a6838146ae97da71c7b79859fd676fda1fc1281e2
package io.xberg;

/**
 * The file validates but cannot be deserialized into [`Preset`].
 */
public class DeserializeException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DeserializeException with the given message. */
  public DeserializeException(final String message) {
    super(message);
  }

  /** Creates a new DeserializeException with the given message and cause. */
  public DeserializeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
