// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f717b49543af890ae0a8627ce3103f9618f119c687de7c33818b0a822cf71af6
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * MIME type detection response.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DetectResponse.Builder.class)
public record DetectResponse(
    @JsonProperty("mime_type") String mimeType,
    @Nullable @JsonProperty("filename") String filename
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for DetectResponse deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("mime_type")
        private String mimeType;
        @Nullable private String filename;

        /** Sets the mimeType field. */
        @JsonProperty("mime_type")
        public Builder withMimeType(final String value) {
            this.mimeType = value;
            return this;
        }

        /** Sets the filename field. */
        @JsonProperty("filename")
        public Builder withFilename(final @Nullable String value) {
            this.filename = value;
            return this;
        }

        /** Constructs a DetectResponse instance from the builder's current state. */
        public DetectResponse build() {
            return new DetectResponse(
                mimeType,
                filename
            );
        }
    }
    // CPD-ON
}
