// DO NOT EDIT - auto-generated by alef
// alef:hash:37c6e4879df791a9b386361fdeb842da47ec91a83a8ca83e3d88ef95cf4eff54
package io.xberg;

/**
 * Errors that can occur during heuristics analysis.
 */
public class HeuristicsErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new HeuristicsErrorException with the given message. */
  public HeuristicsErrorException(final String message) {
    super(message);
  }

  /** Creates a new HeuristicsErrorException with the given message and cause. */
  public HeuristicsErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
