// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3b8c341a2236e98988664875432857696591791246f737912eda57cfef21003c
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Output format for conversion.
 *
 * Specifies the target markup language format for the conversion output.
 */
@SuppressWarnings("PMD")
public enum HtmlToMarkdownRsOutputFormat {
    /**
     * Standard Markdown ({@code CommonMark} compatible). Default.
     */
    Markdown("Markdown"),
    /**
     * Djot lightweight markup language.
     */
    Djot("Djot"),
    /**
     * Plain text output (no markup, visible text only).
     */
    Plain("Plain");


    /** The string value. */
    private final String value;

    HtmlToMarkdownRsOutputFormat(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static HtmlToMarkdownRsOutputFormat fromValue(final String value) {
        for (HtmlToMarkdownRsOutputFormat e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown HtmlToMarkdownRsOutputFormat value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
