// DO NOT EDIT - auto-generated by alef
// alef:hash:5dd069f6b744f56a2fb66ea0ecb9fb140fd536b9c062740cacaaf7d682f92c64
package io.xberg;

/**
 * An image manipulation operation (resize, decode, DPI conversion) failed.
 */
public class ImageProcessingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ImageProcessingException with the given message. */
  public ImageProcessingException(final String message) {
    super(message);
  }

  /** Creates a new ImageProcessingException with the given message and cause. */
  public ImageProcessingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
