// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:36b7934d92e3f7d3cbd28a2d19605edf07d308faf632b495e51b17046a8f4061
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;


/**
 * Bridge interface for the PostProcessor plugin system.
 *
 * Implementations are wrapped by PostProcessorBridge and exposed to the native
 * runtime through Panama FFM upcall stubs.
 */
public interface IPostProcessor {

    /** Plugin name (used for registry keying). */
    String name();

    /** Plugin version. */
    String version();

    /** Initialize the plugin. */
    default void initialize() throws Exception {}

    /** Shut down the plugin. */
    default void shutdown() throws Exception {}

/** process. */    void process(ExtractedDocument result, ExtractionConfig config) throws Exception;

/** processing_stage. */    String processing_stage() throws Exception;

/** should_process. */    boolean should_process(ExtractedDocument _result, ExtractionConfig _config) throws Exception;

/** estimated_duration_ms. */    long estimated_duration_ms(ExtractedDocument _result) throws Exception;

/** priority. */    int priority() throws Exception;
}
