// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0fc78f6198356db378110c5398f2b91a02119ca4c5561e015464069b93462c12
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;


/**
 * Bridge interface for the TokenizerBackend plugin system.
 *
 * Implementations are wrapped by TokenizerBackendBridge and exposed to the native
 * runtime through Panama FFM upcall stubs.
 */
public interface ITokenizerBackend {

    /** Plugin name (used for registry keying). */
    String name();

    /** Plugin version. */
    String version();

    /** Initialize the plugin. */
    default void initialize() throws Exception {}

    /** Shut down the plugin. */
    default void shutdown() throws Exception {}

/** count_tokens. */    long count_tokens(String text) throws Exception;
}
