// DO NOT EDIT - auto-generated by alef
// alef:hash:4367e0e66c75d0105b2991b20a30a0d4f69707829ceee15eaea8789fc6502688
package io.xberg;

/**
 * Errors produced while loading or validating a preset file.
 */
public class LoadErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new LoadErrorException with the given message. */
  public LoadErrorException(final String message) {
    super(message);
  }

  /** Creates a new LoadErrorException with the given message and cause. */
  public LoadErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
