// DO NOT EDIT - auto-generated by alef
// alef:hash:93d8f0848cb90892571c597d93592ee2cc986bc2ec8817527feca8bcabe4b132
package io.xberg;

/**
 * A required optional system dependency (e.g. `tesseract`) was not found.
 */
public class MissingDependencyException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new MissingDependencyException with the given message. */
  public MissingDependencyException(final String message) {
    super(message);
  }

  /** Creates a new MissingDependencyException with the given message and cause. */
  public MissingDependencyException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
