// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5cb6ef0098d4ac814ea469b4ecaf22679c38b9256b74b556b4d5062ee5c7894f
// To regenerate: alef generate
// To verify freshness: alef verify

/**
 * High-performance document intelligence library
 */
package io.xberg;
