// DO NOT EDIT - auto-generated by alef
// alef:hash:d2ebf26176c8bd67d77984b37529cee10cba9c52d54f6e3fbab86f87946148df
package io.xberg;

/**
 * The file is not valid JSON.
 */
public class ParseException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseException with the given message. */
  public ParseException(final String message) {
    super(message);
  }

  /** Creates a new ParseException with the given message and cause. */
  public ParseException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
