// DO NOT EDIT - auto-generated by alef
// alef:hash:35284ff033981de7b8b530954a5ac35bdcd5a270f48cd96313a2db6e707a1493
package io.xberg;

/**
 * A registered plugin returned an error during extraction.
 */
public class PluginException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PluginException with the given message. */
  public PluginException(final String message) {
    super(message);
  }

  /** Creates a new PluginException with the given message and cause. */
  public PluginException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
