// DO NOT EDIT - auto-generated by alef
// alef:hash:a99efcf839715e8cf6189260694243819287a178bda6cdb8ce95935d7f66ac36
package io.xberg;

/**
 * Errors produced while resolving a preset against caller overrides.
 */
public class ResolveErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new ResolveErrorException with the given message. */
  public ResolveErrorException(final String message) {
    super(message);
  }

  /** Creates a new ResolveErrorException with the given message and cause. */
  public ResolveErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
