// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:46b28e487040152f7f143af9972e63c6d32dad9d3c28408a03c960373aa9ad6b
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Controls how markdown tables are handled when they exceed the chunk size limit.
 *
 * Only applies when {@code chunker_type} is {@code Markdown}.
 *
 * # Variants
 *
 * * {@code Split} - Default behavior: tables are split at row boundaries like any
 *   other block element. Continuation chunks contain only data rows without
 *   the header, which can break downstream consumers that need column context.
 * * {@code RepeatHeader} - Prepend the table header (header row + separator row) to
 *   every continuation chunk that contains data rows from the same table.
 *   Adds a small amount of duplicate text but ensures each chunk is
 *   self-contained for extraction, search, and LLM consumption.
 */
@SuppressWarnings("PMD")
public enum TableChunkingMode {
    /**
     * Split tables at row boundaries (default). Continuation chunks have no header.
     */
    Split("split"),
    /**
     * Prepend the table header to every chunk that continues a split table.
     */
    RepeatHeader("repeat_header");


    /** The string value. */
    private final String value;

    TableChunkingMode(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static TableChunkingMode fromValue(final String value) {
        for (TableChunkingMode e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown TableChunkingMode value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
