// DO NOT EDIT - auto-generated by alef
// alef:hash:88b0cd03092758ffb8edd2d088c19848873e6f8a97e3b546f1fd23e9a9fe33b5
package io.xberg;

/**
 * Audio/video transcription failed.
 */
public class TranscriptionException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TranscriptionException with the given message. */
  public TranscriptionException(final String message) {
    super(message);
  }

  /** Creates a new TranscriptionException with the given message and cause. */
  public TranscriptionException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
