// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9b593a689348ee981930f8048adae21176654742d378e6a5254b5b5194b21d75
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;

/**
 * Path A Bridge implementation for IValidator.
 *
 * Wraps a user-supplied implementation and delegates all method calls.
 * This adapter conforms to the hand-authored sealed interface.
 */
public final class ValidatorAdapter implements IValidator {
    private final IValidator impl;

    public ValidatorAdapter(IValidator impl) {
        this.impl = impl;
    }

    @Override
    public String name() {
        return impl.name();
    }

    @Override
    public String version() {
        return impl.version();
    }

    @Override
    public void initialize() throws Exception {
        impl.initialize();
    }

    @Override
    public void shutdown() throws Exception {
        impl.shutdown();
    }

    @Override
    public void validate(ExtractedDocument result, ExtractionConfig config) throws Exception {
        impl.validate(result, config);
    }

    @Override
    public boolean should_validate(ExtractedDocument _result, ExtractionConfig _config) throws Exception {
        return impl.should_validate(_result, _config);
    }

    @Override
    public int priority() throws Exception {
        return impl.priority();
    }


}
