// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:56191559e0a91641a44460a79a9d6bc435aff64f04166e985fe90fc5117bd301
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

/** Exception thrown by XbergRs. */
public class XbergRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new XbergRsException. */
  public XbergRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new XbergRsException with a cause. */
  public XbergRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
