# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1fbef7ec3992747ca8a9171045d2107bf87a9696b4fcabc66ee86a6f292e2d01
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'post_processor_management' do

  it 'post_processors_clear: Clear all post-processors and verify list is empty' do
    expect { Xberg.clear_post_processors() }.not_to raise_error

  end


  it 'post_processors_list: List all registered post-processors' do
    result = Xberg.list_post_processors()

    expect(result).not_to be_nil
  end

end
