# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:902b307d934a1194e6643d9b9113745bbbf4659ba0fcef07926da3d4373d3d58
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'renderer_management' do

  it 'renderers_clear: Clear all renderers and verify list is empty' do
    expect { Xberg.clear_renderers() }.not_to raise_error

  end


  it 'renderers_list: List all registered renderers' do
    result = Xberg.list_renderers()

    expect(result).not_to be_nil
  end

end
