# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:65d8aa3ac324b2cd6ba8ff72f143fcbe0b7e49db09cfbecbd52dbe03d2306270
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'tokenizer_backend_management' do

  it 'tokenizer_backends_clear: Clear all tokenizer backends and verify list is empty' do
    expect { Xberg.clear_tokenizer_backends() }.not_to raise_error

  end


  it 'tokenizer_backends_list: List all registered tokenizer backends' do
    result = Xberg.list_tokenizer_backends()

    expect(result).not_to be_nil
  end

end
