# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:73c70c86b0b71cc6dde88c9c0ee7245420504146c2e2122be9b741ddce361099
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.1.3"
end
