// Generated by alef. Do not edit by hand.
// alef:hash:417221d87ebe5c0064b7b77588316090d171c0610a9f8e4884654ae9f704f1fc
// swift-format-ignore-file
// This file contains generated FFI glue for trait bridge registration.

import Foundation

/// Protocol for outbound `Renderer` implementations.
/// Conform your Swift class or struct to this protocol to implement
/// a Rust trait from the host side.
/// Implementations may be invoked concurrently and must synchronize mutable state.
public protocol SwiftRendererBridge: SwiftPluginBridge {
    /// The Rust trait declares a default body for this method. alef does not carry that body in
    /// its IR and cannot reproduce it, so this conformance is required rather than defaulted:
    /// supply the same value the Rust default would have produced.
    func renderResult(result: String) throws -> String
}

/// Internal adapter wrapping a `SwiftRendererBridge` conformer.
/// Wraps a user-supplied bridge and forwards calls through marshalling entry points.
final class SwiftRendererAdapter {
    private let bridge: any SwiftRendererBridge

    init(bridge: any SwiftRendererBridge) {
        self.bridge = bridge
    }

    // MARK: - SwiftPluginBridge lifecycle

    var name: String {
        return bridge.name
    }

    func version() -> String {
        return bridge.version()
    }

    func initialize() throws {
        try bridge.initialize()
    }

    func shutdown() throws {
        try bridge.shutdown()
    }

    // MARK: - FFI marshalling entry points

    func renderResultCall(result: String) throws -> String {
        do {
            let result = try self.bridge.renderResult(result: result)
            return marshal_ok_result(String(result))
        } catch {
            return marshal_error_result(error)
        }
    }

}

// MARK: - Marshalling helpers

private struct Empty: Codable {}

private func marshal_ok_result<T: Encodable>(_ value: T) -> String {
    let encoder = JSONEncoder()
    if let data = try? encoder.encode(value),
       let jsonString = String(data: data, encoding: .utf8) {
        return "{\"ok\": \(jsonString)}"
    }
    return "{\"ok\": null}"
}

private func marshal_encode_excluded<T: Encodable>(_ value: T) throws -> Data {
    let encoder = JSONEncoder()
    return try encoder.encode(value)
}

private func marshal_error_result(_ error: any Error) -> String {
    let errorString = String(describing: error)
    let encoder = JSONEncoder()
    if let data = try? encoder.encode(errorString),
       let jsonString = String(data: data, encoding: .utf8) {
        return "{\"err\": \(jsonString)}"
    }
    return "{\"err\": \"unknown error\"}"
}
