// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f6254d31acca23d53a208623bcc567b5c60245c9d5ea758dd61ab0126c080940
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Authentication configuration.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = false)
@JsonSubTypes({
    @JsonSubTypes.Type(value = AuthConfig.Basic.class, name = "basic"),
    @JsonSubTypes.Type(value = AuthConfig.Bearer.class, name = "bearer"),
    @JsonSubTypes.Type(value = AuthConfig.Header.class, name = "header")
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
public sealed interface AuthConfig {

    /**
     * HTTP Basic authentication.
     */
    record Basic(
        @JsonProperty("username") String username,
        @JsonProperty("password") String password
    ) implements AuthConfig {
    }

    /**
     * Bearer token authentication.
     */
    record Bearer(@JsonProperty("token") String token) implements AuthConfig { }

    /**
     * Custom authentication header.
     */
    record Header(
        @JsonProperty("name") String name,
        @JsonProperty("value") String value
    ) implements AuthConfig {
    }
}
