// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1ef9a786f2b7ad58a325d37eaeed5830ceb21c8021f02448018fc9b2f7d3c16d
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

/**
 * Chunk-classification enrichment knob: how to multi-label individual chunks.
 *
 * Operates on {@code ExtractedDocument.chunks} in place — the caller must have
 * already produced chunks (e.g. via {@code ExtractionConfig.chunking}) for this
 * stage to have any effect; a document with no chunks is a no-op.
 */
public record ChunkClassificationEnrichmentConfig(ChunkClassificationConfig config) {
}
