// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a778992f5cd59dd3afa1fee3fbf2823218f56b69d20859dd808827951e004dac
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

/** Exception thrown when an FFI value conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends XbergRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConversionErrorException. */
  public ConversionErrorException(final String message) {
    super(1, message);
  }

  /** Creates a new ConversionErrorException with a cause. */
  public ConversionErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
