// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a22f587ca87a61e1dfc8057c97e0e4d98a1cba10ed4c52d9117d4be399618af5
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Footnote in Djot.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Footnote.Builder.class)
public record Footnote(
    @JsonProperty("label") String label,
    @JsonProperty("content") List<FormattedBlock> content
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for Footnote deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private String label;
        private List<FormattedBlock> content = List.of();

        /** Sets the label field. */
        @JsonProperty("label")
        public Builder withLabel(final String value) {
            this.label = value;
            return this;
        }

        /** Sets the content field. */
        @JsonProperty("content")
        public Builder withContent(final List<FormattedBlock> value) {
            this.content = value;
            return this;
        }

        /** Constructs a Footnote instance from the builder's current state. */
        public Footnote build() {
            return new Footnote(
                label,
                content
            );
        }
    }
    // CPD-ON
}
