// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b4572e8928b27c59641d15cefe3b471423496fc7d83616e791819bcd15021335
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;

import java.util.List;

/**
 * Bridge interface for the DocumentExtractor plugin system.
 *
 * Implementations are wrapped by DocumentExtractorBridge and exposed to the native
 * runtime through Panama FFM upcall stubs.
 */
public interface IDocumentExtractor {

    /** Plugin name (used for registry keying). */
    String name();

    /** Plugin version. */
    String version();

    /** Initialize the plugin. */
    default void initialize() throws Exception {}

    /** Shut down the plugin. */
    default void shutdown() throws Exception {}

/** extract. */    ExtractedDocument extract(ExtractInput input, ExtractionConfig config) throws Exception;

/** supported_mime_types. */    List<String> supported_mime_types() throws Exception;

/** priority. */    int priority() throws Exception;

/** can_handle. */    boolean can_handle(java.nio.file.Path _path, String _mime_type) throws Exception;
}
