// DO NOT EDIT - auto-generated by alef
// alef:hash:e25af575d148a649f060ac737bcfcb7cf798bbe25168c166d383d1fdaea23f95
package io.xberg;

/**
 * A filesystem I/O error occurred while reading a preset directory.
 */
public class IoException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IoException with the given message. */
  public IoException(final String message) {
    super(message);
  }

  /** Creates a new IoException with the given message and cause. */
  public IoException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
