// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5b70bacb646daf8c6394a77c5ab8150a27488ab1ae70081372f8480944bf8f35
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;

import java.util.List;

/**
 * Bridge interface for the RerankerBackend plugin system.
 *
 * Implementations are wrapped by RerankerBackendBridge and exposed to the native
 * runtime through Panama FFM upcall stubs.
 */
public interface IRerankerBackend {

    /** Plugin name (used for registry keying). */
    String name();

    /** Plugin version. */
    String version();

    /** Initialize the plugin. */
    default void initialize() throws Exception {}

    /** Shut down the plugin. */
    default void shutdown() throws Exception {}

/** rerank. */    List<Float> rerank(String query, List<String> documents) throws Exception;
}
