// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1357687216792f9e2d0dbbdd5e8382b8e6676ce21f73a5dfbed419b0e62906de
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;


/**
 * Bridge interface for the Validator plugin system.
 *
 * Implementations are wrapped by ValidatorBridge and exposed to the native
 * runtime through Panama FFM upcall stubs.
 */
public interface IValidator {

    /** Plugin name (used for registry keying). */
    String name();

    /** Plugin version. */
    String version();

    /** Initialize the plugin. */
    default void initialize() throws Exception {}

    /** Shut down the plugin. */
    default void shutdown() throws Exception {}

/** validate. */    void validate(ExtractedDocument result, ExtractionConfig config) throws Exception;

/** should_validate. */    boolean should_validate(ExtractedDocument _result, ExtractionConfig _config) throws Exception;

/** priority. */    int priority() throws Exception;
}
