// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:67183824b92ad3a546b9f1afad454db2c9bd9ec55553e2f6a329b4bc4872bd22
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Language detection configuration.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LanguageDetectionConfig.Builder.class)
public record LanguageDetectionConfig(
    @Nullable @JsonProperty("enabled") Boolean enabled,
    @Nullable @JsonProperty("min_confidence") Double minConfidence,
    @Nullable @JsonProperty("detect_multiple") Boolean detectMultiple
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }
    public LanguageDetectionConfig{
        if (enabled == null) { enabled = true; }
        if (minConfidence == null) { minConfidence = 0.8; }
    }

    // CPD-OFF
    /** Jackson builder for LanguageDetectionConfig deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @Nullable private Boolean enabled;
        @JsonProperty("min_confidence")
        @Nullable private Double minConfidence;
        @JsonProperty("detect_multiple")
        @Nullable private Boolean detectMultiple;

        /** Sets the enabled field. */
        @JsonProperty("enabled")
        public Builder withEnabled(final @Nullable Boolean value) {
            this.enabled = value;
            return this;
        }

        /** Sets the minConfidence field. */
        @JsonProperty("min_confidence")
        public Builder withMinConfidence(final @Nullable Double value) {
            this.minConfidence = value;
            return this;
        }

        /** Sets the detectMultiple field. */
        @JsonProperty("detect_multiple")
        public Builder withDetectMultiple(final @Nullable Boolean value) {
            this.detectMultiple = value;
            return this;
        }

        /** Constructs a LanguageDetectionConfig instance from the builder's current state. */
        public LanguageDetectionConfig build() {
            return new LanguageDetectionConfig(
                enabled,
                minConfidence,
                detectMultiple
            );
        }
    }
    // CPD-ON
}
