// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ec5c561d935a66fb4550a30d9be1096493bd7d9456e8027c58e63566217fd1c4
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

/** Exception thrown when a Rust panic is contained at the FFI boundary. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class PanicException extends XbergRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PanicException. */
  public PanicException(final String message) {
    super(3, message);
  }

  /** Creates a new PanicException with a cause. */
  public PanicException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
