// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:738ca85c2bbe2d6bf7577b6f2083cc7e64b68ccf342d11a9962bb148a5cb54d3
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Semantic classification of a tracked change.
 */
@SuppressWarnings("PMD")
public enum RevisionKind {
    /**
     * Text or content was inserted.
     */
    Insertion("insertion"),
    /**
     * Text or content was deleted.
     */
    Deletion("deletion"),
    /**
     * Run-level formatting (font, size, colour, …) was changed.
     */
    FormatChange("format_change"),
    /**
     * A reviewer comment or annotation.
     */
    Comment("comment");


    /** The string value. */
    private final String value;

    RevisionKind(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static RevisionKind fromValue(final String value) {
        for (RevisionKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown RevisionKind value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
