// DO NOT EDIT - auto-generated by alef
// alef:hash:94448223105e2089b8dc38c6f78c5015303cd6a2ef99a7abc86851a5702b51de
package io.xberg;

/**
 * A security policy was violated (e.g. zip bomb, oversized archive).
 */
public class SecurityException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SecurityException with the given message. */
  public SecurityException(final String message) {
    super(message);
  }

  /** Creates a new SecurityException with the given message and cause. */
  public SecurityException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
