// DO NOT EDIT - auto-generated by alef
// alef:hash:8227fa965fa6007a7de39a2f16eaec7397a42419cd67211f8a25ea26f45f0ad6
package io.xberg;

/**
 * The document's MIME type is not supported by any registered extractor.
 */
public class UnsupportedFormatException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new UnsupportedFormatException with the given message. */
  public UnsupportedFormatException(final String message) {
    super(message);
  }

  /** Creates a new UnsupportedFormatException with the given message and cause. */
  public UnsupportedFormatException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
